<form>
    <label>
        <span class="inputbox-label">Key:</span>
        <div class="order-inputbox-holder">
            <div class='api-credentials-key'><?=$this->credentialsKey;?></div>
        </div>
    </label>
    <label>
        <span class="inputbox-label">Secret:</span>
        <div class="order-inputbox-holder">
            <div class='api-credentials-secret'><?=$this->credentialsSecret;?></div>
        </div>
    </label>
    <label>
        <span class="inputbox-label">Documentation:</span>
        <div class="order-inputbox-holder">
            <div class='api-documentation'><a href="<?=$this->remoteUrl('/api', 'developer');?>" target="_blank"><?=$this->remoteUrl('/api', 'developer');?></a></div>
        </div>
    </label>
</form>