<?php $this->inlineScript()->captureStart(); ?>
require.config({
    paths: {
        'ManualOrder': '<?= $this->basePath() . Orders\Module::PUBLIC_FOLDER; ?>/js/ManualOrder',
        'Product': '<?= $this->basePath() . Products\Module::PUBLIC_FOLDER; ?>/js/Product'
    }
});
require(['ManualOrder/ManualOrder', 'ManualOrder/Utils'], function(ManualOrderRoot, ManualOrderUtils) {
    var manualOrderUtils = new ManualOrderUtils('<?= $this->basePath() . Products\Module::PUBLIC_FOLDER; ?>img');
    var manualOrdersRoot = new ManualOrderRoot(document.getElementById('product-information'), manualOrderUtils);
});
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->placeholder('#sidebar')->set($this->sidebar); ?>

<div class="module clearfix section-separator" id="product-information">

</div>

<div class="module clearfix section-separator" id="order-buyer-message">

</div>

<div class="module clearfix section-separator" id="address-information">

</div>

<div class="module clearfix section-separator" id="order-alert">

</div>

<div class="module clearfix section-separator" id="order-notes">

</div>