<?php $this->placeholder('#sidebar')->set($this->sidebar); ?>

<div class="module clearfix section-separator" id="product-information">

</div>

<div class="module clearfix section-separator" id="order-buyer-message">

</div>

<div class="module clearfix section-separator" id="address-information">

</div>

<div class="module clearfix section-separator" id="order-alert">

</div>

<div class="module clearfix section-separator" id="order-notes">

</div>