<?php $this->inlineScript()->captureStart(); ?>
require.config({
    paths: {
        'ManualOrder': '<?= $this->basePath() . Orders\Module::PUBLIC_FOLDER; ?>/js/ManualOrder',
        'Product': '<?= $this->basePath() . Products\Module::PUBLIC_FOLDER; ?>/js/Product',
        'Common': '<?= $this->basePath() ?>/cg-built/common/js/Common'
    }
});
require(
    ['ManualOrder/ManualOrder', 'Common/Utils/Carrier', 'Common/Utils/Currency', 'Common/Utils/Image'],
    function(ManualOrderRoot, CarrierUtils, CurrencyUtils, ImageUtils) {

    var utilities = {
        carrier: new CarrierUtils({ carriersList: JSON.parse('<?= $carriersJson ?>') }),
        currency: new CurrencyUtils({ currenciesList: JSON.parse('<?= $currenciesJson ?>') }),
        image: new ImageUtils({ imageBasePath: '<?= $this->basePath() . Products\Module::PUBLIC_FOLDER; ?>img' })
    };
    var manualOrdersRoot = new ManualOrderRoot(document.getElementById('product-information'), utilities);
});
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->placeholder('#sidebar')->set($this->sidebar); ?>
<?php $this->headLink()->appendStylesheet($this->basePath() .'/cg-built/common/css/default.css', ['screen', 'print']) ?>

<div class="module clearfix section-separator" id="product-information">
    <?php #React Mount Node ?>
</div>

<div class="module clearfix section-separator manual-order" id="order-buyer-message">
    <?= $this->buyerMessage ?>
</div>

<div class="module clearfix section-separator" id="address-information">

</div>

<div class="module clearfix section-separator" id="order-alert">

</div>

<div class="module clearfix section-separator" id="order-notes">

</div>