<?php /* The following scripts can't be loaded with require() as that happens asynchronously and we need this NOW */ ?>
<script type="text/javascript" src="<?=Orders\Module::PUBLIC_FOLDER;?>js/Courier/DataTableAbstract.js"></script>
<script type="text/javascript" src="<?=Orders\Module::PUBLIC_FOLDER;?>js/Courier/Specifics/DataTable.js"></script>
<script type="text/javascript">
$(document).ready(function()
{
    var courierOrderIds = <?=json_encode($this->courierOrderIds);?>;
    var courierAccountId = <?=$this->selectedCourier->getId();?>;
    var orderServices = <?=json_encode($this->orderServices);?>;
    var specificsDataTable = new CourierSpecificsDataTable($('#datatable'), courierOrderIds, courierAccountId, orderServices);

    require(['<?=Orders\Module::PUBLIC_FOLDER;?>js/Courier/Specifics/Service.js'], function(Service)
    {
        var service = new Service($('#datatable'), courierAccountId);
    });
});
</script>
<div id="main" class="courier-specifics">
    <span class="heading-large">
        <div style="float:left"><span class="logo-large <?=$this->selectedCourier->getChannel();?>"></span></div>
        <div class="heading-buttons" id="courier-specifics-bulk-actions" style="display:none">
            <div class="backorders_btn button-holder">
                <a href="/orders" class="button"><?=$this->translate('Back To Orders');?></a>
            </div>
            <?=$this->bulkActionsButtons;?>
        </div>
    </span>
    <div id="datatable-container">
        <?= $this->specificsTable; ?>
    </div>
    <div style="display:none">
        <?=$this->serviceSelect;?>
        <?=$this->parcelsElement;?>
        <?=$this->collectionDateElement;?>
        <div id="courier-itemParcelAssignment-button-container">
            <?=$this->itemParcelAssignmentButton;?>
        </div>
        <div id="courier-action-buttons">
            <?=$this->actionsButtons;?>
        </div>
        <form method="POST" action="/orders/courier/label/print" id="courier-specifics-label-form">
            <?php /* order input(s) will be added by JS like:
            <input type="hidden" name="order[]" value="" /> */ ?>
            <input type="hidden" name="account" value="<?=$this->selectedCourier->getId();?>" />
        </form>
    </div>
</div>