<?php /* The following scripts can't be loaded with require() as that happens asynchronously and we need this NOW */ ?>
<script type="text/javascript" src="<?=Orders\Module::PUBLIC_FOLDER;?>js/Courier/DataTableAbstract.js"></script>
<script type="text/javascript" src="<?=Orders\Module::PUBLIC_FOLDER;?>js/Courier/Specifics/DataTable.js"></script>
<script type="text/javascript">
$(document).ready(function()
{
    var courierOrderIds = <?=json_encode($this->courierOrderIds);?>;
    var courierId = <?=$this->selectedCourier->getId();?>;
    var orderServices = <?=json_encode($this->orderServices);?>;
    var specificsDataTable = new CourierSpecificsDataTable($('#datatable'), courierOrderIds, courierId, orderServices);

    require(['<?=Orders\Module::PUBLIC_FOLDER;?>js/Courier/Specifics/Service.js'], function(Service)
    {
        var service = new Service($('#datatable'));
    });
});
</script>
<div id="main" class="courier-specifics">
    <span class="heading-large">
        <?= $this->selectedCourier->getDisplayName().' '.$this->translate('Orders') ?>
        <div class="heading-buttons">
            <?= $this->createAllLabelsButton; ?>
        </div>
    </span>
    <div id="datatable-container">
        <?= $this->specificsTable; ?>
    </div>
    <div style="display:none">
        <?=$this->serviceSelect;?>
        <?=$this->parcelsElement;?>
        <div id="courier-action-buttons">
            <?=$this->actionsButtons;?>
        </div>
    </div>
</div>