require.config({
    paths: {
        "Product/BulkAction/ListingsImport": "<?= $this->baseUrl . Products\Module::PUBLIC_FOLDER . 'js/Product/BulkAction/ListingsImport' ?>"
    }
});

require(["Product/BulkAction/ListingsImport"], function(ListingsImport)
{
    var updateOptions = <?= $updateOptions ?>;
    var listingsImportMap = new ListingsImport("<?= $selector ?>", updateOptions);
    listingsImportMap.init(<?= json_encode($this->templateMap) ?>);
});
