require.config({
    paths: {
        "Product/BulkAction/StockImport": "<?= $this->baseUrl . Products\Module::PUBLIC_FOLDER . 'js/Product/BulkAction/StockImport' ?>"
    }
});

require(["Product/BulkAction/StockImport"], function(StockImport)
{
    var updateOptions = <?= $updateOptions ?>;
    var stockImportAction = new StockImport("<?= $selector ?>", updateOptions);
    stockImportAction.init(<?= json_encode($this->templateMap) ?>);
});
