require.config({
    paths: {
        "Product/BulkAction/StockExport": "<?= $this->baseUrl . Products\Module::PUBLIC_FOLDER . 'js/Product/BulkAction/StockExport' ?>"
    }
});

require(["Product/BulkAction/StockExport"], function(StockExport)
{
    var stockExportAction = new StockExport(n, "<?= $selector ?>");
    $("#<?= $id ?>").bulkActions("set", "<?= $action ?>", function() {
        stockExportAction.action();
    });
});
