require.config({
    paths: {
        StockExport: "<?= $this->baseUrl . Products\Module::PUBLIC_FOLDER . 'js/Product/BulkAction/StockExport' ?>",
        ProgressCheckAbstract: "<?= $this->baseUrl . Orders\Module::PUBLIC_FOLDER . 'js/ProgressCheckAbstract' ?>"
    }
});

require(['Product/BulkAction/StockExport'], function(StockExport)'])
{
    var stockExportAction = new StockExport();
    stockExportAction.init(<?= json_encode($this->templateMap) ?>);
}
