require.config({
    paths: {
        StockImport: "<?= $this->baseUrl . Products\Module::PUBLIC_FOLDER . 'js/Product/BulkAction/StockImport' ?>"
    }
});

require(['Product/BulkAction/StockImport'], function(StockImport)
{
    var updateOptions = <?= $updateOptions ?>;
    var stockImportAction = new StockImport(n, updateOptions);
    stockImportAction.init(<?= json_encode($this->templateMap) ?>);
    $("#<?= $id ?>").bulkActions("set", "<?= $action ?>", function() {
        stockImportAction.setSelector("<?= $selector ?>");
        stockImportAction.action();
    });
});
