let elementTypes = {
    INPUT_SAFE_SUBMITS: 'INPUT_SAFE_SUBMITS',
    SELECT_DROPDOWN: 'SELECT_DROPDOWN',
    STOCK_MODE_SELECT_DROPDOWN: 'STOCK_MODE_SELECT_DROPDOWN'
};

export default elementTypes;