<?php $this->placeholder('#sub-header')->append($filters); ?>
<?php $this->headLink()->appendStylesheet($this->basePath() .'/cg-built/vendor/cg-common/dist/css/default.css', ['screen', 'print']) ?>
<div id="bulk-actions" class="sales-report">
    <?php echo $hideFilters; ?>
</div>
<?php //$this->headScript()->appendFile($this->basePath() . '/cg-built/vendor/chart.js/dist/Chart.bundle.js'); ?>

<?php $this->inlineScript()->captureStart(); ?>
    $(document).ready(function() {
        require.config({
            paths: {
                'Reports': "<?=$this->basePath() . Reports\Module::PUBLIC_FOLDER . 'js/Reports';?>"
            }
        });
        require([
            'Reports/Application'
        ], function(
            ReportsApp
        ) {
            let app = new ReportsApp();
            app.buildSalesChart();
        });
    });
<?php $this->inlineScript()->captureEnd(); ?>

<span class="spinner-container" style="display: flex; justify-content: center;">
    <div alt="Loading" class="indicator-sizer -default u-margin-right-small" style="height: 50px; width:50px; margin-top:15rem;">
        <?=
            $this->mustache(
                'elements/loadingIndicator.mustache'
            )
        ?>
    </div>
</span>


<div class="chart-container">
    <canvas id="salesChart"></canvas>
</div>
