<?php $this->headLink()->appendStylesheet($this->basePath() .'/cg-built/vendor/cg-common/dist/css/default.css', ['screen', 'print']) ?>
<?php $this->placeholder('#sub-header')->append($filters); ?>
<div id="bulk-actions" class="sales-report">
    <?php echo $hideFilters; ?>
</div>
<?php //$this->headScript()->appendFile($this->basePath() . '/cg-built/vendor/chart.js/dist/Chart.bundle.js'); ?>

<?php $this->inlineScript()->captureStart(); ?>
    $(document).ready(function() {
        require.config({
            paths: {
                'Reports': "<?=$this->basePath() . Reports\Module::PUBLIC_FOLDER . 'js/Reports';?>"
            }
        });
        require([
            'Reports/Application'
        ], function(
            ReportsApp
        ) {
            let app = new ReportsApp();
            app.buildSalesChart();
        });
    });
<?php $this->inlineScript()->captureEnd(); ?>

<div class="spinner-container" style="display:flex; justify-content: center; height:100%">
    <div class="spinner-positioner">
        <div alt="Loading" class="indicator-sizer" style="height: 5rem; width: 5rem;">
            <?=
            $this->mustache(
                'elements/loadingIndicator.mustache'
            )
            ?>
        </div>
    </div>
</div>

<div class="chart-container">
    <canvas id="salesChart"></canvas>
</div>
