<?php foreach ($fields as $field): ?>
<?php if ($field->getAttribute('type') != 'hidden'): ?>
<div class="account-field-holder">
    <label>
        <div class="label inputbox-label">
            <?= $this->translate($field->getOption('label')); ?>:
            <?php if ($field->getOption('required')):?>
            <abbr class="required">*</abbr>
            <?php endif;?>
        </div>
        <div class="text-field order-inputbox-holder">
            <?= $this->formInput($field); ?>
        </div>
    </label>
</div>
<?php else: ?>
<?= $this->formInput($field); ?>
<?php endif; ?>
<?php endforeach; ?>