<?php

use CG_Channel\Module as ChannelModule;

if (isset($accountPendingInstructions)) {
    echo $accountPendingInstructions;
    return;
}

if (isset($testPackFiles)) {
    echo $this->partial('courier-adapter/settings_account/test_pack_files.phtml', compact('account', 'testPackFiles'));
}

if (isset($configForm)) {
    echo $this->partial('courier-adapter/settings_account/config.phtml', compact('account', 'configForm'));
}

if (isset($testModeInstructions)) {
    echo $this->partial('courier-adapter/settings_account/test_mode_instructions.phtml', compact('testModeInstructions'));
}
echo $this->partial(ChannelModule::TEMPLATE_TOKEN_RENEWAL_HREF, compact('account', 'form', 'route', 'url'));