<?php

use CG_Channel\Module as ChannelModule;

if ($this->accountPendingInstructions) {
    echo $this->accountPendingInstructions;
    return;
}

if (isset($configFields)) {
    echo $this->partial('courier-adapter/settings_account_config.phtml', compact('account', 'configFields', 'configSaveUrl'));
}

echo $this->partial(ChannelModule::TEMPLATE_TOKEN_RENEWAL_HREF, compact('account', 'form', 'route', 'url'));