<?php $this->inlineScript()->captureStart(); ?>
    $(document).ready(function() {
        require.config({
            paths: {
                'Common': '<?= $this->basePath() ?>/cg-built/vendor/cg-common/dist/js',
                'PickListSettings': "<?= $this->basePath() . Settings\Module::PUBLIC_FOLDER . 'js/PickListSettings' ?>"
            }
        });
        require(['PickListSettings/PickListSettings'], function(PickListSettings) {
            new PickListSettings(
                document.getElementById('picklist-settings'),
                <?= json_encode($this->eTag) ?>,
                <?= json_encode($this->pickList) ?>,
                <?= json_encode($this->sortFields) ?>,
                <?= json_encode($this->sortFieldsMap) ?>,
                <?= json_encode($this->sortDirections) ?>,
                <?= json_encode($this->saveRoute) ?>,
                <?= json_encode($this->isPickLocationsEnabled) ?>
            );
        });
    });
<?php $this->inlineScript()->captureEnd(); ?>

<div id="breadcrumbs" class="floatLeftClear">
  <span class="heading-large">
    <?= $this->translate($title) ?>
  </span>
</div>
<div id="picklist-settings" class="module clearfix"></div>
