<?= $this->partial('value.phtml', compact('value')) ?>
<?php $this->inlineScript()->captureStart() ?>
    require(['<?= Orders\Module::PUBLIC_FOLDER ?>js/Courier/Specifics/Columns/EoriNumber.js'], function(EoriNumber)
    {
        var templatePath = "<?=CG_UI\Module::PUBLIC_FOLDER;?>templates/elements/custom-select.mustache";
        var eoriNumber = new EoriNumber(templatePath);
    });
<?php $this->inlineScript()->captureEnd() ?>