# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: channelgrabber/php71

pipelines:
  default:
    - step:
        name: Composer Install
        caches:
          - composer
        script:
          - >
            sed -i 's/"shasum": "[^"]*"/"shasum": null/g' composer.lock
          - composer install --no-ansi --no-progress --no-suggest --prefer-dist --ignore-platform-reqs --no-scripts --optimize-autoloader
        artifacts:
          - vendor/**
    - parallel:
        - step:
            name: Unit Tests
            script:
              - vendor/bin/phpunit --log-junit ./test-reports/junit.xml
        - step:
            name: Static Analysis
            script:
              - mkdir -p ./test-reports
              - vendor/bin/phpstan analyse --error-format junit > ./test-reports/junit.analysis.xml