<?php $this->headLink()->appendStylesheet($this->basePath() .'/cg-built/vendor/cg-common/dist/css/default.css', ['screen', 'print']) ?>

<?php $this->inlineScript()->captureStart(); ?>
require.config({
    paths: {
        'Templates': '<?= $this->basePath() . DataExchange\Module::PUBLIC_FOLDER; ?>/js/DataExchange/Templates',
        'Common': '<?= $this->basePath() ?>/cg-built/vendor/cg-common/dist/js/Common'
    }
});
$(document).ready(function() {
    const rootNode = document.getElementById('orders-templates-root');
    require([
        "Templates/Orders/Index",
    ],
    function(
        OrdersTemplatesIndex
    ) {
        new OrdersTemplatesIndex(
            rootNode,
            <?= json_encode($this->templates) ?>,
            <?= json_encode($this->cgFieldOptions) ?>
        );
    });
});
<?php $this->inlineScript()->captureEnd(); ?>

<div id="breadcrumbs" class="floatLeftClear u-defloat">
    <h2 class="heading-large u-defloat">
        Orders Templates
    </h2>
</div>
<div class="module clearfix">
    <div id="orders-templates-root" class="u-clear-both u-margin-top-med"></div>
</div>