<?php
use Settings\Module;
use Settings\Controller\ChannelController;
$enableChannelRoute = implode(
    '/',
    [
        Module::ROUTE,
        ChannelController::ROUTE,
        ChannelController::ROUTE_CHANNELS,
        ChannelController::ROUTE_ACCOUNT,
        ChannelController::ROUTE_ACCOUNT_STATUS,
    ]
);
?>
<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function()
{
    $('#account_details_form input[type="submit"]').click(function(e)
    {
        e.preventDefault();
        n.notice('Updating channel account');
        $('#settings_account_form_royal_mail').submit();

        $('#settings_account_form_royal_mail').on('success', function() {
            $('#account_details_form').submit();
        });

        $('#account_details_form').on('success', function(e, json) {
            n.success(json.status);
        });

        $(document).on('fail', '#settings_account_form_royal_mail', function(e, json) {
            n.error(json.message);
        });

        $(document).on('fail', '#account_details_form',  function(e, json) {
            n.error(json.message);
        });
        return false;
    });
});

require.config({
    paths: {
        enableChannel: "<?= Settings\Module::PUBLIC_FOLDER ?>js/enableChannel"
    }
});

require(
    ["enableChannel"],
    function(enableChannel) {
        var ajaxCheckbox = enableChannel(
            n,
            ".account-status .mustache",
            "input.toggle",
            {
                url: "<?= $this->url($enableChannelRoute, ['account' => $account['id'], 'type' => $type]) ?>"
            },
            {
                info: "<?= $this->translate('Updating Sales Channel Status') ?>",
                error: "<?= $this->translate('Updating Sales Channel Status') ?>",
                success: "<?= $this->translate('Sales Channel Status Updated') ?>"
            }
        );

        CGMustache.get().fetchTemplates(
            {
                enable: "<?= Module::PUBLIC_FOLDER ?>template/columns/enable.mustache",
                status: "<?= Module::PUBLIC_FOLDER ?>template/columns/status.mustache"
            },
            function(template, cgmustache) {
                ajaxCheckbox.bindAjaxResponse(function(event, data) {
                    if (!data.account) {
                        return;
                    }

                    var status = $(ajaxCheckbox.getBaseSelector()).empty();
                    status.append(cgmustache.renderTemplate(template, data.account, "enable"));
                    status.append(cgmustache.renderTemplate(template, data.account, "status"));
                });
            }
        );
    }
);
<?php $this->inlineScript()->captureEnd(); ?>
<div id="breadcrumbs" class="floatLeftClear">
    <span class="heading-large"><?= $account['displayName'] ?><span class="logo-large <?= $account['channel'] ?>"></span></span>
</div>
<div class="module clearfix">
    <form class="account-status">
        <label>
            <span class="inputbox-label">Enable Account:</span>
            <div class="alternate-input mustache">
                <?= $this->mustache('columns/enable.mustache', $account) ?>
                <span class="current-account-status">
                  <?= $this->mustache('columns/status.mustache', $account) ?>
                </span>
            </div>
        </label>
    </form>
</div>
<div id="manage-account-channel-form" class="module clearfix section-separator">
    <?= $this->channelSpecificForm;?>
    <?php
    $detailsForm->prepare();
    $detailsForm->setAttribute('class', 'ajaxPost');
    ?>
    <?= $this->form()->openTag($detailsForm) ?>
        <?= $this->formHidden($detailsForm->get('csrf')); ?>
        <div class="half">
            <label>
                <span class="inputbox-label">Display Name:<abbr class="required">*</abbr></span>
                <div class="order-inputbox-holder">
                    <?= $this->formText($detailsForm->get('displayName')); ?>
                </div>
            </label>
            <label>
                <span class="inputbox-label">Trading Company:</span>

                <?= $this->formHidden($detailsForm->get('organisationUnitId')); ?>
                <div class="order-inputbox-holder">
                    <div class="input"><?= $tradingCompanySelect; ?></div>
                </div>
            </label>
            <label>
                <div class="order-inputbox-holder">
                    <?= $this->formButton($detailsForm->get('save')); ?>
                    <span class="loading">Saving</span>
                </div>
            </label>
        </div>
    <?= $this->form()->closeTag(); ?>
</div>
