<?php
use Settings\Module;
use Settings\Controller\ChannelController;
$enableChannelRoute = implode(
    '/',
    [
        Module::ROUTE,
        ChannelController::ROUTE,
        ChannelController::ROUTE_CHANNELS,
        ChannelController::ROUTE_ACCOUNT,
        ChannelController::ROUTE_ACCOUNT_STATUS,
    ]
);
?>
<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function()
{
    $('#account_details_form').submit(function()
    {
        n.notice('Updating channel account');
    });
});

require.config({
    paths: {
        ajaxSwitch: "<?= Settings\Module::PUBLIC_FOLDER ?>js/ajaxSwitch"
    }
});

require(
    ["ajaxSwitch"],
    function(ajaxSwitch) {
        var ajaxCheckbox = ajaxSwitch(
            n,
            ".account-status .mustache",
            "input.toggle",
            {
                url: "<?= $this->url($enableChannelRoute, ['account' => $account['id'], 'type' => $type]) ?>"
            },
            {
                info: "<?= $this->translate('Updating Channel Status') ?>",
                error: "<?= $this->translate('Updating Channel Status') ?>",
                success: "<?= $this->translate('Channel Status Updated') ?>"
            }
        );

        CGMustache.get().fetchTemplates(
            {
                enable: "<?= Module::PUBLIC_FOLDER ?>template/columns/enable.mustache",
                status: "<?= Module::PUBLIC_FOLDER ?>template/columns/accountStatus.mustache"
            },
            function(template, cgmustache) {
                ajaxCheckbox.bindAjaxResponse(function(event, data) {
                    if (!data.account) {
                        return;
                    }

                    var status = $(ajaxCheckbox.getBaseSelector()).empty();
                    status.append(cgmustache.renderTemplate(template, data.account, "enable"));
                    status.append(cgmustache.renderTemplate(template, data.account, "status"));
                });
            }
        );
    }
);
<?php $this->inlineScript()->captureEnd(); ?>
<div id="breadcrumbs" class="floatLeftClear">
    IM IN THIS VIEW
    <span class="heading-large"><?= $account['displayName'] ?><?= $this->channel ;?></span>
</div>
<div class="module clearfix">
    <form class="account-status">
        <label>
            <span class="inputbox-label">Enable Account:</span>
            <div class="alternate-input mustache">
                <?= $this->mustache('columns/enable.mustache', $account) ?>
                <span class="current-account-status">
                  <?= $this->mustache('columns/accountStatus.mustache', $account) ?>
                </span>
            </div>
        </label>
    </form>
</div>
<div id="manage-account-channel-form" class="module clearfix section-separator">
    HERE TIS
    <?= $this->channelSpecificForm;?>
   
</div>
<div class="module clearfix section-separator">
     HERE TISNT
    <?php
    $detailsForm->prepare();
    $detailsForm->setAttribute('class', 'ajaxPost');
    ?>
    <?= $this->form()->openTag($detailsForm) ?>
        <?= $this->formHidden($detailsForm->get('csrf')); ?>
        <div class="half">
            <label>
                <span class="inputbox-label">Display Name:<abbr class="required">*</abbr></span>
                <div class="order-inputbox-holder">
                    <?= $this->formText($detailsForm->get('displayName')); ?>
                </div>
            </label>
            <label>
                <span class="inputbox-label">Trading Company:</span>

                <?= $this->formHidden($detailsForm->get('organisationUnitId')); ?>
                <div class="order-inputbox-holder">
                    <div class="input"><?= $tradingCompanySelect; ?></div>
                </div>
            </label>
            <div class="order-inputbox-holder">
              <?= $this->formButton($detailsForm->get('save')); ?>
              <span class="loading">Saving</span>
            </div>            
        </div>
    <?= $this->form()->closeTag(); ?>
</div>
