<?php $this->headLink()->appendStylesheet($this->basePath() . Settings\Module::PUBLIC_FOLDER . 'css/channelList.css') ?>
<?php $this->headScript()->appendFile($this->basePath() . CG_UI\Module::PUBLIC_FOLDER . 'js/mustache.js'); ?>
<?php $this->headScript()->appendFile($this->basePath() . CG_UI\Module::PUBLIC_FOLDER . 'js/cg-mustache.js'); ?>
<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function() {
    require(["settings/SettingsPage", "settings/account"],
        function(SettingsPage, Account) {
            var settingsPage = new SettingsPage(new Account());
        }
    );
});
<?php $this->inlineScript()->captureEnd(); ?>
<h1 class="title"><?= $this->translate($title) ?></h1>
<div class="account_create large-dropdown" data-url="<?= $this->url(Settings\Module::ROUTE . '/' .
    Settings\Controller\ChannelController::ROUTE . '/' . Settings\Controller\ChannelController::CREATE_ROUTE); ?>">
    <div class="input">
        <?= $addChannelSelect; ?>
    </div>
    <input type="submit" class="button inline account-save" value="<?= $this->translate('Add'); ?>"/>
</div>
<?= $this->accountList ?>