<?php $this->headLink()->appendStylesheet($this->basePath() .'/cg-built/vendor/cg-common/dist/css/default.css', ['screen', 'print']) ?>

<?php $this->inlineScript()->captureStart(); ?>
require.config({
    paths: {
        'Listing': '<?= $this->basePath() . '/cg-built/settings/js/Listing'?>'
    }
});
$(document).ready(function() {
    let rootNode = document.getElementById('listing-templates-root');
    require([
        "Listing/ListingTemplates",
    ],
        function(
            ListingTemplates
        ) {
            var listingTemplates = new ListingTemplates(
                rootNode,
                <?= $this->templates ?>,
                <?= $this->listingTemplateTags ?>
            );
        }
    );
});
<?php $this->inlineScript()->captureEnd(); ?>

<div id="breadcrumbs" class="floatLeftClear">
    <span class="heading-large">
        Ebay Listing Templates
    </span>
</div>
<div class="module clearfix">
    <div id="listing-templates-root" class="u-clear-both u-margin-top-med"></div>
</div>