<?php $this->inlineScript()->captureStart(); ?>
require.config({
    paths: {
        'EmailDesigner': "<?=$this->basePath() . Settings\Module::PUBLIC_FOLDER . 'js/EmailDesigner';?>"
    }
});
require(['EmailDesigner/EmailDesigner'], function(EmailDesigner)
{
    var mountingNodes = {
        emailDesignerRoot: document.getElementById('email-designer-mount')
    };
    new EmailDesigner(mountingNodes);
});
<?php $this->inlineScript()->captureEnd(); ?>
<div id="email-designer">
    <div id="email-designer-mount"></div>
</div>