<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function() {
    require.config({
        paths: {
            'ShippingAlias': "<?=$this->basePath() . Settings\Module::PUBLIC_FOLDER . 'js/ShippingAlias';?>"
        }
    });
    var shippingMethods = $.parseJSON('<?= json_encode($shippingMethods); ?>');
    var shippingAccounts = $.parseJSON('<?= json_encode($shippingAccounts); ?>');
    var rootOuId = <?=$rootOuId;?>;
    require([
        'ShippingAlias/DomManipulator',
        'ShippingAlias/MethodCollection',
        'ShippingAlias/AccountCollection',
        'ShippingAlias/DomListener/AddButton',
        'ShippingAlias/DomListener/DeleteButton',
        'ShippingAlias/DomListener/AliasChange',
        'ShippingAlias/DomListener/AccountChange',
        'ShippingAlias/Mapper'
    ], function(
        domManipulator,
        methodCollection,
        accountCollection,
        addButtonListener,
        deleteButtonListener,
        aliasChangeListener,
        accountChangeListener,
        mapper
    ) {
        $(document).ready(function()
        {
            methodCollection.setItems(mapper.fromCollectionToOptions(shippingMethods));
            var accountOptions = mapper.fromCollectionToOptions(shippingAccounts);
            accountOptions.unshift({
                title: 'None',
                value: '0'
            });
            accountCollection.setItems(accountOptions);

            addButtonListener.init();
            deleteButtonListener.init(rootOuId);
            aliasChangeListener.init(rootOuId);
            accountChangeListener.init();

            domManipulator.updateAllAliasMethodCheckboxes();
        });
    });
});
<?php $this->inlineScript()->captureEnd(); ?>
<div class="padded-content-holder">
    <div class="shipping-alias-wrapper">
        <span class="heading-large">
            <?= $this->translate($title) ?>
            <div class="add-settings">
            <?= $addButton ?>
            </div>
        </span>
        <div id="shipping-alias-container">
            <?= $aliases ?>
        </div>
    </div>
</div>
