<?php $this->headLink()->appendStylesheet($this->basePath() .'/cg-built/vendor/cg-common/dist/css/default.css', ['screen', 'print']) ?>

<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function() {
    require.config({
        paths: {
            'ShippingAlias': "<?=$this->basePath() . Settings\Module::PUBLIC_FOLDER . 'js/ShippingAlias';?>"
        }
    });
    var shippingMethods = <?= json_encode($shippingMethods); ?>;
    var shippingAccountOptions = <?= json_encode($shippingAccountOptions); ?>;
    var rootOuId = <?=$rootOuId;?>;
    var templatePath = '<?=$this->basePath() . CG_UI\Module::PUBLIC_FOLDER . 'templates/';?>';
    require(['ShippingAlias/Service'], function(Service)
    {
        $(document).ready(function()
        {
            var service = new Service(shippingMethods, shippingAccountOptions, rootOuId, templatePath);
        });
    });
});
<?php $this->inlineScript()->captureEnd(); ?>
<div class="padded-content-holder">
    <div class="shipping-alias-wrapper">
        <span class="heading-large">
            <?= $this->translate($title) ?>
            <div class="add-settings">
            <?= $addButton ?>
            </div>
        </span>
        <div id="shipping-alias-container">
            <?= $aliases ?>
        </div>
    </div>
</div>
