<?php $this->headLink()->appendStylesheet($this->basePath() . CG_UI\Module::PUBLIC_FOLDER . 'css/common/subheader-hide.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath() . Settings\Module::PUBLIC_FOLDER . 'css/invoiceDesigner.css') ?>
<?php $this->inlineScript()->captureStart(); ?>
var templateSelectorId = "#<?= $templateSelectorId; ?>";

$(document).on('click', '.toPdfButton', function() {
    require([
        'InvoiceDesigner/Template/Inspector/Service',
        'InvoiceDesigner/Template/Service'
    ], function(InspectorService, InvoiceDesignerService) {
        var template = InspectorService.getTemplate();
        var templateJson = InvoiceDesignerService.getMapper().toJson(template);
        InvoiceDesignerService.showAsPdf(templateJson);
    });
});

var paperTypeDropdownId = "#<?= $paperTypeDropdownId; ?>";

$(document).ready(function() {
    require.config({
        paths: {
            'InvoiceDesigner': "<?=$this->basePath() . Settings\Module::PUBLIC_FOLDER . 'js/InvoiceDesigner';?>"
        }
    });
    require(['InvoiceDesigner/Application'], function(designerApp)
    {
        designerApp.init();
    });
});
<?php $this->inlineScript()->captureEnd(); ?>
<div id="invoice-controls-bar" class="sidebar sidebar-fixed sidebar-left sidebar-invoice-designer">
    <!--Invoice Controls-->

    <form method="post" action="/orders/invoice/preview" class="button toPdfButton" style="margin: 10px">
        To Pdf
        <input name="template" type="hidden" />
    </form>
    <hr>

    <!--Invoice Template-->
    <div class="invoice-select-create">
        <?= $templates; ?>
        <?= $templateAddButton ?>
        <?= $templateDuplicateButton ?>
    </div>
    <div id="template-name-container" class="template-module template-name-container">
        <div><?= $this->translate('Template Name'); ?></div>
        <?= $templateName; ?>
    </div>
    <?= $paperTypeModule ?>

    <div class="addInvoiceElement">
        <div class="addInvoiceElementTitle">Add Element</div>
    </div>
</div>
<div id="invoice-template" class="invoice-template">
    <div id="save-template" class='save-template'>
        <div class="save-template-message"><?= $this->translate('You have made changes that are currently not saved'); ?></div>
        <div class="save-template-buttons">
            <?= $templateDiscardButton ?>
            <?= $templateSaveButton ?>
        </div>
    </div>
    <div id="invoice-template-container" class="invoice-template-container">
    </div>

</div>
<div id="element-inspector-bar" class="sidebar sidebar-fixed sidebar-right sidebar-invoice-designer">
    <!--Element Inspectors-->
    <div id="heading-inspector"></div>
</div>
