<?php $this->headLink()->appendStylesheet($this->basePath() . CG_UI\Module::PUBLIC_FOLDER . 'css/common/subheader-hide.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath() . Settings\Module::PUBLIC_FOLDER . 'css/invoice-designer.css') ?>
<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function() {
    require.config({
        paths: {
            'InvoiceDesigner': "<?=$this->basePath() . Settings\Module::PUBLIC_FOLDER . 'js/InvoiceDesigner';?>"
        }
    });

    require(['InvoiceDesigner/Application'], function(designerApp)
    {
        designerApp.init();
    });

/*
 * TEMP testing code
 */
require(['InvoiceDesigner/Template/Mapper', 'InvoiceDesigner/Template/Service'], function(mapper, service)
{
var json = {
    id: 1,
    name: "Example",
    type: "invoice",
    organisationUnitId: 1,
    minHeight: 0,
    minWidth: 0,
    elements: [{
        type: "page",
        width: 250,
        height: 353,
        backgroundImage: "http://lakeshorechurch.org.au/wp-content/uploads/2013/02/rough-beige-paper-texture.jpg"
    }, {
        type: "box",
        width: 20,
        height: 20,
        x: 5,
        y: 5,
        backgroundColour: "#000080",
        borderWidth: 2,
        borderColour: "#008000"
    }, {
        type: "text",
        width: 50,
        height: 30,
        x: 30,
        y: 5,
        backgroundColour: "#fff",
        fontSize: 10,
        fontFamily: "monospace",
        fontColour: "#999",
        text: "This is an example text element with\nnewline",
        padding: 2,
        lineHeight: 3,
        align: "center"
    }, {
        type: "deliveryAddress",
        width: 70,
        height: 30,
        x: 85,
        y: 5,
        backgroundColour: "#ccc",
        fontSize: 10,
        fontFamily: "monospace",
        fontColour: "#000",
        text: "1 The Street\nThe Town\nThe City\nTE1 1ST",
        padding: 2
    }, {
        type: "sellerAddress",
        width: 70,
        height: 30,
        x: 160,
        y: 5,
        backgroundColour: "#ccc",
        fontSize: 10,
        fontFamily: "monospace",
        fontColour: "#000",
        text: "The Company\nThe Business Park\nThe Town\nThe City\nTE1 1ST",
        padding: 2
    }, {
        type: "orderTable",
        width: 200,
        height: 100,
        x: 5,
        y: 40,
        borderWidth: 1,
        borderColour: "#000"
    }]
};
var template = mapper.fromJson(json);
service.render(template);
});
});
<?php $this->inlineScript()->captureEnd(); ?>
<div id="invoice-controls-bar" class="sidebar sidebar-fixed sidebar-left sidebar-invoice-designer">
    <!--Invoice Controls-->
</div>
<div id="invoice-template-container" class="invoice-template-container">
    <!--Invoice Template-->
</div>
<div id="element-inspector-bar" class="sidebar sidebar-fixed sidebar-right sidebar-invoice-designer">
    <!--Element Inspectors-->
</div>