<?php $this->headLink()->appendStylesheet($this->basePath() . CG_UI\Module::PUBLIC_FOLDER . 'css/common/subheader-hide.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath() . Settings\Module::PUBLIC_FOLDER . 'css/invoiceDesigner.css') ?>
<?php $this->inlineScript()->captureStart(); ?>
var templateSelectorId = "#<?= $templateSelectorId; ?>";
$(document).ready(function() {
    require.config({
        paths: {
            'InvoiceDesigner': "<?=$this->basePath() . Settings\Module::PUBLIC_FOLDER . 'js/InvoiceDesigner';?>"
        }
    });

    require(['InvoiceDesigner/Application'], function(designerApp)
    {
        designerApp.init();
    });
});
<?php $this->inlineScript()->captureEnd(); ?>
<div id="invoice-controls-bar" class="sidebar sidebar-fixed sidebar-left sidebar-invoice-designer">
    <!--Invoice Controls-->
    <div class="invoice-select-create">
        <?= $templates; ?>
        <?= $templateAddButton ?>
        <?= $templateDuplicateButton ?>
    </div>
    <div id="template-name-container" class="template-name-container">
        <div><?= $this->translate('Template Name'); ?></div>
        <?= $templateName; ?>
    </div>
</div>
<div id="invoice-template" class="invoice-template">
    <div id="save-template" class='save-template'>
        <div class="save-template-message"><?= $this->translate('You have made changes that are currently not saved'); ?></div>
        <div class="save-template-buttons">
            <?= $templateDiscardButton ?>
            <?= $templateSaveButton ?>
        </div>
    </div>
    <div id="invoice-template-container" class="invoice-template-container">
    </div>
</div>
<div id="element-inspector-bar" class="sidebar sidebar-fixed sidebar-right sidebar-invoice-designer">
    <!--Element Inspectors-->
    <div id="heading-inspector"></div>
    <div id="positioning-inspector"></div>
</div>