<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function() {
    require.config({
        paths: {
            'InvoiceOverview': "<?=$this->basePath() . Settings\Module::PUBLIC_FOLDER . 'js/InvoiceOverview';?>"
        }
    });
    require(['InvoiceOverview/InvoiceOverview'], function(InvoiceOverview)
    {
        var mountingNode = document.getElementById('invoice-overview-mount');
// *TEMPORARY*
        var invoiceTemplates = {
            templates: [
                0: {
                    name: 'FPS-16 Template',
                    id: 'fps16',
                    links: [
                        0: {
                            name: 'Create',
                            url: 'https://www.formsplus.co.uk/online-shop/integrated/single-integrated-labels/fps-3/?utm_source=Channel%20Grabber&utm_medium=Link%20&utm_campaign=FPS-3%20CG%20Link'
                        },
                        1: {
                        }
                    ]
                },
                1: {
                    name: 'FPS-15 Template',
                    id: 'fps15',
                    links: [
                        0: {
                            name: 'Create',
                            url: 'https://www.formsplus.co.uk/online-shop/integrated/single-integrated-labels/fps-3/?utm_source=Channel%20Grabber&utm_medium=Link%20&utm_campaign=FPS-3%20CG%20Link'
                        },
                        1: {
                        }
                    ]
                },
                2: {
                    name: 'FPS-14 Template',
                    id: 'fps14',
                    links: [
                        0: {
                            name: 'Create',
                            url: 'https://www.formsplus.co.uk/online-shop/integrated/single-integrated-labels/fps-3/?utm_source=Channel%20Grabber&utm_medium=Link%20&utm_campaign=FPS-3%20CG%20Link'
                        },
                        1: {
                        }
                    ]
                }
            ],
            existing: [
            ]
        };
        new InvoiceOverview(mountingNode, invoiceTemplates);
    });
});
<?php $this->inlineScript()->captureEnd(); ?>
<div id="invoiceOverview">
    <form>
        <input type='hidden' value="<?= $eTag ?>" id="setting-etag">
        <div id="invoice-overview-mount"></div>
        <div class="invoice-template-section module">
            <div class="heading-large">Create New Invoice</div>
            <div class="invoice-template-element">
                <div class="invoice-template-thumb"></div>
                <div class="invoice-template-name">Blank Invoice</div>
                <div class="invoice-template-actions">
                    <div class="invoice-template-action-link create">Create</div>
                </div>
            </div>
            <div class="invoice-template-element">
                <div class="invoice-template-thumb">
                    <img src="/cg-built/settings/img/InvoiceOverview/TemplateThumbnails/Form-FPS3.png">
                </div>
                <div class="invoice-template-name">FPS-3 Template</div>
                <div class="invoice-template-actions">
                    <div class="invoice-template-action-link create">Create</div>
                    <div class="invoice-template-action-link purchase">Purchase Label</div>
                </div>
            </div>
            <div class="invoice-template-element">
                <div class="invoice-template-thumb">
                    <img src="/cg-built/settings/img/InvoiceOverview/TemplateThumbnails/Form-FPS15.png">
                </div>
                <div class="invoice-template-name">FPS-15 Template</div>
                <div class="invoice-template-actions">
                    <div class="invoice-template-action-link create">Create</div>
                    <div class="invoice-template-action-link purchase">Purchase Label</div>
                </div>
            </div>
            <div class="invoice-template-element">
                <div class="invoice-template-thumb">
                    <img src="/cg-built/settings/img/InvoiceOverview/TemplateThumbnails/Form-FPS16.png">
                </div>
                <div class="invoice-template-name">FPS-16 Template</div>
                <div class="invoice-template-actions">
                    <div class="invoice-template-action-link create">Create</div>
                    <div class="invoice-template-action-link purchase">Purchase Label</div>
                </div>
            </div>
            <div class="invoice-template-element">
                <div class="invoice-template-thumb">
                    <img src="/cg-built/settings/img/InvoiceOverview/TemplateThumbnails/Form-FPD1.png">
                </div>
                <div class="invoice-template-name">FPD-1 Template</div>
                <div class="invoice-template-actions">
                    <div class="invoice-template-action-link create">Create</div>
                    <div class="invoice-template-action-link purchase">Purchase Label</div>
                </div>
            </div>
        </div>
        <div class="invoice-template-section module">
            <div class="heading-large">Edit Existing Invoice</div>
            <div class="invoice-template-element">
                <div class="invoice-template-thumb">

                </div>
                <div class="invoice-template-name">Main Default with extra long name deffo 1</div>
                <div class="invoice-template-actions">
                    <div class="invoice-template-action-link edit">Edit</div>
                    <div class="invoice-template-action-link delete">Delete</div>
                </div>
            </div>
            <div class="invoice-template-element">
                <div class="invoice-template-thumb">

                </div>
                <div class="invoice-template-name">Main 2</div>
                <div class="invoice-template-actions">
                    <div class="invoice-template-action-link edit">Edit</div>
                    <div class="invoice-template-action-link delete">Delete</div>
                </div>
            </div>
        </div>
    </form>
</div>