<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function() {
    require.config({
        paths: {
            'Settings': "<?=$this->basePath() . Settings\Module::PUBLIC_FOLDER . 'js';?>"
        }
    });
    require([
        'Settings/invoiceSettings',
        'element/Factory/Select'
    ], function(
        InvoiceSettings,
        select
    ) {
        new InvoiceSettings('<?= $hasAmazonAccount;?>', '<?= json_encode($tagOptions); ?>');

        $(document).on('fnDrawCallback', function(event, data) {
            $('.invoiceTradingCompaniesCustomSelect').each(function() {
                select.init($(this).attr('name'));
            });
        });
    });
});
<?php $this->inlineScript()->captureEnd(); ?>
<div class="invoiceSettings">
    <form>
        <input type='hidden' value="<?= $eTag ?>" id="setting-etag">
        <div class="invoiceDefaultSettings module half">
            <div class="heading-large">Invoice Settings</div>
            <label>
                <span class="inputbox-label">Show Item Barcodes:</span>
                <div class="checkbox-holder">
                    <?= $itemBarcodesCheckbox ?>
                </div>
            </label>
            <label>
                <span class="inputbox-label">Include Item Sku:</span>
                <div class="checkbox-holder">
                    <?= $itemSkuCheckbox ?>
                </div>
            </label>
            <label>
                <span class="inputbox-label">Include Product Images:</span>
                <div class="checkbox-holder">
                    <?= $productImagesCheckbox ?>
                </div>
            </label>
            <label>
                <span class="inputbox-label">Email Invoice on Dispatch:</span>
                <div class="checkbox-holder">
                    <?= $autoEmailToggle ?>
                </div>
            </label>
            <div class="emailInvoiceFields">

                <div id="emailInvoiceNotification" class="relative-notifications <?php if ($emailSendAs && $emailVerified) { echo 'hidden'; } ?>">
                    <div class="notifications">
                        <div class="clearfix error">
                            <span class="icon"><span>&amp;tick;</span></span><span class="content">Invoices won’t be emailed until you’ve successfully verified an email address to send from</span>
                        </div>
                    </div>
                </div>

                <label class="email-send-as-label">
                    <span class="inputbox-label">Send From Email:</span>
                    <div class="email-send-as-holder">
                        <?= $emailSendAsInput ?>

                        <?php if (isset($emailVerificationStatus)): ?>
                            <?= $emailVerificationStatus ?>
                        <?php endif; ?>

                        <button id="emailVerifyButton" data-id="<?= $invoiceSettings->getId() ?>" class="button inline email-verify-button <?php if ($emailSendAs) { echo 'hidden'; } ?>">Verify</button>
                    </div>
                </label>
                <label class="email-bcc-label">
                <span class="inputbox-label">Email Myself a Copy:</span>
                    <div class="copy-required-holder">
                        <?= $copyRequiredCheckbox ?>
                    </div>
                    <div class="email-bcc-holder">
                        <?= $emailBccInput ?>
                    </div>
                </label>
                <label class="email-send-as-label">
                    <span class="inputbox-label">Invoice Email Template:</span>
                </label>
                <div class="invoice-email-editor-section">
                    <div id="invoice-email-editor">
                        <?= $emailTemplate ?? '' ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="invoiceTradingCompanySettings module section-separator">
            <div class="heading-large">Trading Company Email Settings</div>
            <?php if (empty($tradingCompanies)) : ?>
                (No Trading companies exist)
            <?php else : ?>
                <?= $this->invoiceSettingsDataTable ?>
            <?php endif; ?>
        </div>
    </form>
</div>
<div class="invoiceMapping">
    <form>
        <div class="invoiceMappingTable module section-separator">
            <div class="heading-large">Invoice Mapping</div>
            <div class="invoiceDefaultSettings half">
                <label>
                    <span class="inputbox-label">Default Invoice:</span>
                    <div class="invoice-settings-field order-inputbox-holder half-input">
                        <?= $defaultCustomSelect; ?>
                    </div>
                </label>
            </div>
            <?= $this->invoiceMappingTable ?>
        </div>
    </form>
</div>