<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function() {
    require.config({
        paths: {
            'Settings': "<?=$this->basePath() . Settings\Module::PUBLIC_FOLDER . 'js';?>"
        }
    });
    require([
        'Settings/invoiceSettings',
        'element/Factory/Select'
    ], function(
        InvoiceSettings,
        select
    ) {
        var tradingCompanyColumnIndex = 2;
        var hasTradingCompanies = <?= empty($tradingCompanies) ? 'false' : 'true' ?>;
        var lastAccountId = 0;
        var evenRow = true;
        new InvoiceSettings(
            '<?= $this->basePath() . Settings\Module::PUBLIC_FOLDER ?>',
            '<?= $amazonSite ;?>',
            '<?= json_encode($tagOptions); ?>'
        );

        $(document).on('fnInitComplete', function(event, oSettings) {
            var table = $('#invoiceMapping').dataTable();
            table.fnSetColumnVis(tradingCompanyColumnIndex, hasTradingCompanies);
        });

        $(document).on('fnDrawCallback', function(event, data) {
            $('.invoiceTradingCompaniesCustomSelect').each(function() {
                select.init($(this).attr('name'));
            });
        });

        $(document).on('fnRowCallback', function(event, nRow, aData)
        {
            if ($(nRow).hasClass('even-row') || $(nRow).hasClass('odd-row')) {
                return;
            }

            $(nRow).addClass('invoice-mapping-row').attr('data-element-row-id', aData.rowId);

            sameAccount = (lastAccountId === aData.accountId);
            if(! sameAccount) {
                $(nRow).addClass('account-row')
                evenRow = (!evenRow);
            }
            rowType = (evenRow ? 'even' : 'odd');

            var className = rowType+'-row';
            $(nRow).addClass(className);
            lastAccountId = aData.accountId;
        });
    });
});
<?php $this->inlineScript()->captureEnd(); ?>
<div class="invoiceSettings">
    <form>
        <input type='hidden' value="<?= $eTag ?>" id="setting-etag">
        <div class="invoiceDefaultSettings module half">
            <div class="heading-large">Global Settings</div>
            <label>
                <span class="inputbox-label">Show Item Barcodes:</span>
                <div class="checkbox-holder">
                    <?= $itemBarcodesCheckbox ?>
                </div>
            </label>
            <label>
                <span class="inputbox-label">Include Item Sku:</span>
                <div class="checkbox-holder">
                    <?= $itemSkuCheckbox ?>
                </div>
            </label>
            <label>
                <span class="inputbox-label">Include Product Images:</span>
                <div class="checkbox-holder">
                    <?= $productImagesCheckbox ?>
                </div>
            </label>
            <label>
                <span class="inputbox-label">Include Variation Attributes:</span>
                <div class="checkbox-holder">
                    <?= $itemVariationAttributesCheckbox ?>
                </div>
            </label>
            <div class="emailInvoiceFields">

                <div id="emailInvoiceNotification" class="relative-notifications <?php if ($emailSendAs && $emailVerified) { echo 'hidden'; } ?>">
                    <div class="notifications">
                        <div class="clearfix error">
                            <span class="icon"><span>&amp;tick;</span></span><span class="content">Invoices won’t be emailed until you’ve successfully verified an email address to send from</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="invoiceTradingCompanySettings module section-separator">
            <div class="heading-large">Trading Company Email Settings</div>
            <?php if (empty($tradingCompanies)) : ?>
                (No Trading companies exist)
            <?php else : ?>
                <?= $this->invoiceSettingsDataTable ?>
            <?php endif; ?>
        </div>
    </form>
</div>
<div class="invoiceMapping">
    <form>
        <div class="invoiceMappingTable module section-separator">
            <div class="heading-large">Invoice Settings</div>
            <div class="invoiceMappingSettings half">
                <label class="email-send-as-label">
                    <span class="inputbox-label">Send From Email:</span>
                    <div class="email-send-as-holder">
                        <?= $emailSendAsInput ?>

                        <?php if (isset($emailVerificationStatus)): ?>
                            <?= $emailVerificationStatus ?>
                        <?php endif; ?>

                        <button id="emailVerifyButton" data-id="<?= $invoiceSettings->getId() ?>" class="button inline email-verify-button <?php if ($emailSendAs) { echo 'hidden'; } ?>">Verify</button>
                    </div>
                </label>
                <label class="email-bcc-label">
                    <span class="inputbox-label">Email Myself a Copy:</span>
                    <div class="invoice-settings-field copy-required-holder">
                        <?= $copyRequiredCheckbox ?>
                    </div>
                    <div class="invoice-settings-field email-bcc-holder">
                        <?= $emailBccInput ?>
                    </div>
                </label>
            </div>
            <?= $this->invoiceMappingTable ?>
        </div>
    </form>
</div>
