<div class="setup-wizard-complete setup-wizard-complete-thanks">
    <img src="<?=  SetupWizard\Module::PUBLIC_FOLDER;?>img/thankYouIcon.png" width="306" height="310" alt="Thank you" />
    <span>Thank you, <span class="setup-wizard-complete-name"><?=$this->name;?></span>.</span>
</div>
<div class="setup-wizard-complete setup-wizard-complete-congrats">
    Congratulations, you have successfully setup your <span class="setup-wizard-complete-oh">OrderHub</span> account. Now enjoy selling faster!
</div>
<script type="text/javascript">
    require(['<?=SetupWizard\Module::PUBLIC_FOLDER;?>js/steps/Complete.js'], function(Complete)
    {
        new Complete();
    });
</script>