<div class="module clearfix">
    <?= $this->productInfo ?>
</div>

<div class="module clearfix">
    <h1 style="float: initial;">Stock Log</h1>
    <h2>Historic stock levels</h2>
    <?= $this->stockLog ?>
</div>

<div class="module clearfix">
    <h1 style="float: initial;">Stock Adjustment Log</h1>
    <h2>The adjustments that have been applied to this stock</h2>
    <?= $this->stockAdjustmentLog ?>
</div>
