export default {
    productExpand: 'productExpand',
    image: 'image',
    link: 'link',
    sku: 'sku',
    name: 'name',
    available: 'available',
    listingAccount: 'listingAccount',
    addListing: 'addListing',
    stockMode: 'stockMode',
    weight: 'weight',
    dimensions: 'dimensions',
    lowStock: 'lowStock',
    reorderQuantity: 'reorderQuantity',
    pickingLocation: 'pickingLocation',
    cost: 'cost',
    fulfillmentLatency: 'fulfillmentLatency',
    barcode: 'barcode',
    barcodeNotApplicable: 'barcodeNotApplicable',
    supplier: 'supplier'
};