<?php $this->headLink()->appendStylesheet($this->basePath() . CG_UI\Module::PUBLIC_FOLDER . 'css/common/subheader-hide.css'); ?>
<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function() {
    require.config({
        paths: {
            'Messages': "<?=$this->basePath() . Messages\Module::PUBLIC_FOLDER . 'js/Messages';?>",
            'InvoiceDesigner': "<?=$this->basePath() . Settings\Module::PUBLIC_FOLDER . 'js/InvoiceDesigner';?>"
        }
    });
    require([
        'Messages/Application'
    ], function(
        MessagesApp
    ) {
        new MessagesApp(<?=$rootOuId;?>);
    });
});
<?php $this->inlineScript()->captureEnd(); ?>

<div class="message-center-nav">
    <ul>
        <li>Loading...</li>
    </ul>
</div>
<div class="main-section">
    <div class="message-pane">
        <ul>
            <li>Loading...</li>
        </ul>
    </div>
    <div class="message-preview">No conversations selected</div>
</div>