<?php $this->headLink()->appendStylesheet($this->basePath() . CG_UI\Module::PUBLIC_FOLDER . 'css/common/subheader-hide.css', ['screen', 'print']); ?>
<?php $this->headLink()->appendStylesheet($this->basePath() .'/cg-built/vendor/cg-common/dist/css/default.css', ['screen', 'print']) ?>
<?php $this->headLink()->appendStylesheet($this->basePath() . Messages\Module::PUBLIC_FOLDER . 'css/default.css', ['screen', 'print']); ?>
<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function() {
    require.config({
        paths: {
            'Messages': "<?=$this->basePath() . Messages\Module::PUBLIC_FOLDER . 'js/';?>",
            'InvoiceDesigner': "<?=$this->basePath() . Settings\Module::PUBLIC_FOLDER . 'js/InvoiceDesigner';?>"
        }
    });
    require([
        'Messages/Index'
    ], function(
        MessagesIndex
    ) {
        var assignableUsers = <?=json_encode($assignableUsersArray);?>;
        var singleUserMode = <?= (count($assignableUsersArray) == 1) ? 1 : 0; ?>;
        var mountingNode = document.getElementById('app-mount-node');
        MessagesIndex(mountingNode, {
            uri: <?=$this->jsString($uri);?>,
            rootOuId: <?=$rootOuId;?>,
            assignableUsers: assignableUsers,
            singleUserMode: singleUserMode,
            threadId: <?=($threadId ? $this->jsString($threadId) : 'null');?>,
            filter: <?=($filter ? $this->jsString($filter) : 'null');?>,
            filterValue: <?=($filterValue ? $this->jsString($filterValue) : 'null');?>,
            messageTemplates: <?= json_encode($messageTemplates); ?>,
            messageTemplateTags: <?= json_encode($messageTemplateTags); ?>,
            accounts: <?= json_encode($accounts); ?>
        });
    });
});
<?php $this->inlineScript()->captureEnd(); ?>

<div id="app-mount-node" class="module clearfix section-separator"></div>
