<?php $this->headLink()->appendStylesheet($this->basePath() . CG_UI\Module::PUBLIC_FOLDER . 'css/common/subheader-hide.css', ['screen', 'print']); ?>
<?php $this->headLink()->appendStylesheet($this->basePath() .'/cg-built/vendor/cg-common/dist/css/default.css', ['screen', 'print']) ?>
<?php $this->headLink()->appendStylesheet($this->basePath() . Messages\Module::PUBLIC_FOLDER . 'css/default.css', ['screen', 'print']); ?>
<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function() {
    require.config({
        paths: {
            'Messages': "<?=$this->basePath() . Messages\Module::PUBLIC_FOLDER . 'js/Messages';?>",
            'InvoiceDesigner': "<?=$this->basePath() . Settings\Module::PUBLIC_FOLDER . 'js/InvoiceDesigner';?>"
        }
    });
    require([
        'Messages/Application'
    ], function(
        MessagesApp
    ) {
        var assignableUsers = <?=json_encode($assignableUsersArray);?>;
        var singleUserMode = <?= (count($assignableUsersArray) == 1) ? 1 : 0; ?>;
        new MessagesApp(
            <?=$this->jsString($uri);?>,
            <?=$rootOuId;?>,
            assignableUsers,
            singleUserMode,
            <?=($threadId ? $this->jsString($threadId) : 'null');?>,
            <?=($filter ? $this->jsString($filter) : 'null');?>,
            <?=($filterValue ? $this->jsString($filterValue) : 'null');?>
        );
    });
});
<?php $this->inlineScript()->captureEnd(); ?>

<div id="app-mount-node" class="module clearfix section-separator"></div>
