<?php $this->inlineScript()->captureStart(); ?>
require([
    "showHideFilters"
],
function(showHideFilters) {
    var showHideFilters = new showHideFilters();
});
require.config({
    paths: {
        'Filters': "<?= $this->basePath() . Filters\Module::PUBLIC_FOLDER . 'js';?>"
    }
});
require(["Filters/FilterCollection"], function(filterCollection) {
    var filterNames = {
<?php
    foreach ($filterNames as $index => $filterName) {
        echo $filterName . ": '" . $filterName . "', ";
    }
?>
    };
    filterCollection.setFilters(filterNames);
});
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->headScript()->appendFile($this->basePath() . Filters\Module::PUBLIC_FOLDER . 'js/dataTableFilters.js'); ?>
<?php $this->headScript()->appendFile($this->basePath() . Products\Module::PUBLIC_FOLDER . 'js/Listing/mustache-formatters.js'); ?>
<?php $this->placeholder('#main.class')->append('full-width'); ?>
<?php $this->placeholder('#sub-header')->append($filters); ?>
<div id="main" class="transition-preload module clearfix<?= $this->placeholder('#main.class')->setPrefix(' ')->setIndent(1) ?>">
    <?= $this->breadcrumbs; ?>
    <?= $this->bulkItems; ?>
    <div id="listings-list">
        <?= $this->listings; ?>
    </div>
</div>
<script type="text/javascript">
</script>
<style>
    /**
      This is a hack to hide the sidebar away for now TODO: Remove this
      When introducing filters (ie Saved Filters)
    **/
    #main-wrapper {
        margin-left:0px;
        width:100%;
    }

    #listings-list {
        margin-top:50px;
    }
</style>