<?php $this->inlineScript()->captureStart(); ?>
require([
    "showHideFilters"
],
function(showHideFilters) {
    var showHideFilters = new showHideFilters();
});
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->placeholder('#main.class')->append('full-width'); ?>
<div id="main" class="transition-preload module clearfix<?= $this->placeholder('#main.class')->setPrefix(' ')->setIndent(1) ?>">
    <?= $this->breadcrumbs; ?>
    <?= $this->bulkItems; ?>
    <div id="listings-list">
        <?= $this->listings; ?>
    </div>
</div>
<script type="text/javascript">
</script>
<style>
    /**
      This is a hack to hide the sidebar away for now TODO: Remove this
      When introducing filters (ie Saved Filters)
    **/
    #main-wrapper {
        margin-left:0px;
        width:100%;
    }

    #listings-list {
        margin-top:50px;
    }
</style>