<?php
use CG\Locale\CountryNameByCode;
use CG_UI\Form\Element\Text\Country as CountrySelect;
?>
<div id="detailsForm">
    <form id="addressInformation" data-url="<?= $this->url($addressSaveUrl, ($order ? array('order' => $order->getId()) : [])); ?>"
          data-actionMessage="<?= $this->translate('Updating address'); ?>" data-successMessage="<?= $this->translate('Address updated'); ?>">
        <input type="hidden" id="eTag" name="eTag" value="<?=  $order && $order->getUserChange() ? $order->getUserChange()->getStoredETag() : null; ?>">
        <div class="half" id="billing-information">
                <span class="heading-large heading-spacing"><?= $this->translate('Billing Information'); ?>
                    <?php if ($includeAddressCopy): ?>
                    <a class="copy-address-to-clipboard" id="copy-billing-address"><?= $this->translate("Copy address to clipboard"); ?></a>
                    <?php endif; ?>
                </span>
            <?php if ($includeUseBillingInfo): ?>
                <label>
                    <span class="inputbox-label"></span><div class="order-inputbox-holder"></div>
                </label>
            <?php endif; ?>
            <label>
                <span class="inputbox-label"><?= $this->translate('Buyer Name'); ?></span>
                <div class="order-inputbox-holder">
                    <input class="inputbox copy-address" type="text" name="billingAddressFullName" value="<?=  $order ? $order->getCalculatedBillingAddressFullName() : ''; ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                </div>
            </label>
            <label>
                <span class="inputbox-label"><?= $this->translate('Company Name'); ?></span>
                <div class="order-inputbox-holder">
                    <input class="inputbox copy-address" type="text" name="billingAddressCompanyName" value="<?=  $order ? $order->getCalculatedBillingAddressCompanyName() : ''; ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                </div>
            </label>
            <label>
                <span class="inputbox-label"><?= $this->translate('Address Line 1'); ?></span>
                <div class="order-inputbox-holder">
                    <input class="inputbox copy-address" type="text" name="billingAddress1" value="<?=  $order ? $order->getCalculatedBillingAddress1() : ''; ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                </div>
            </label>
            <label>
                <span class="inputbox-label"><?= $this->translate('Address Line 2'); ?></span>
                <div class="order-inputbox-holder">
                    <input class="inputbox copy-address" type="text" name="billingAddress2" value="<?=  $order ? $order->getCalculatedBillingAddress2() : ''; ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                </div>
            </label>
            <label>
                <span class="inputbox-label"><?= $this->translate('Address Line 3'); ?></span>
                <div class="order-inputbox-holder">
                    <input class="inputbox copy-address" type="text" name="billingAddress3" value="<?=  $order ? $order->getCalculatedBillingAddress3() : ''; ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                </div>
            </label>
            <label>
                <span class="inputbox-label"><?= $this->translate('City'); ?></span>
                <div class="order-inputbox-holder">
                    <input class="inputbox copy-address" type="text" name="billingAddressCity" value="<?=  $order ? $order->getCalculatedBillingAddressCity() : ''; ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                </div>
            </label>
            <label>
                <span class="inputbox-label"><?= $this->translate('County'); ?></span>
                <div class="order-inputbox-holder">
                    <input class="inputbox copy-address" type="text" name="billingAddressCounty" value="<?=  $order ? $order->getCalculatedBillingAddressCounty() : ''; ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                </div>
            </label>
            <label>
                <span class="inputbox-label"><?= $this->translate('Postcode'); ?></span>
                <div class="order-inputbox-holder">
                    <input class="inputbox copy-address" type="text" name="billingAddressPostcode" value="<?=  $order ? $order->getCalculatedBillingAddressPostcode() : ''; ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                </div>
            </label>
            <label>
                <span class="inputbox-label"><?= $this->translate('Country'); ?></span>
                <?=
                $this->mustache(
                    'elements/custom-select.mustache',
                    [
                        'holder' => 'order-inputbox-holder',
                        'class' => 'copy-address',
                        'name' => 'billingAddressCountry',
                        'searchField' => true,
                        'initialValue' => $order ? $order->getCalculatedBillingAddressCountry() : '',
                        'options' => CountrySelect::getDefaultCountryOptions(CountryNameByCode::getCountryNameFromCode($order ? $order->getCalculatedBillingAddressCountry() : '', false)),
                        'disabled' => !$this->editable,
                    ]
                )
                ?>
            </label>
            <label>
                <span class="inputbox-label"><?= $this->translate('Email'); ?></span>
                <div class="order-inputbox-holder">
                    <input class="inputbox" type="text" name="billingEmailAddress" value="<?=  $order ? $order->getCalculatedBillingEmailAddress() : ''; ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                </div>
            </label>
            <label>
                <span class="inputbox-label"><?= $this->translate('Telephone'); ?></span>
                <div class="order-inputbox-holder">
                    <input class="inputbox" type="text" name="billingPhoneNumber" value="<?=  $order ? $order->getCalculatedBillingPhoneNumber() : ''; ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                </div>
            </label>
        </div>
        <div class="half"  id="shipping-information">
                <span class="heading-large heading-spacing"><?= $this->translate('Shipping Information'); ?>
                    <?php if ($includeAddressCopy): ?>
                        <a class="copy-address-to-clipboard" id="copy-shipping-address"><?= $this->translate("Copy address to clipboard"); ?></a>
                    <?php endif; ?>
                </span>
            <?php if ($includeUseBillingInfo): ?>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Use Billing Information'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="checkbox" name="shippingAddressUseBilling" />
                    </div>
                </label>
            <?php endif; ?>
            <?php if (!$order || !$order->getFulfilmentAddress()): ?>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Recipient Name'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="shippingAddressFullName" value="<?=  $order ? $order->getCalculatedShippingAddressFullName() : ''; ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Company Name'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="shippingAddressCompanyName" value="<?=  $order ? $order->getCalculatedShippingAddressCompanyName() : ''; ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Address Line 1'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="shippingAddress1" value="<?=  $order ? $order->getCalculatedShippingAddress1() : ''; ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Address Line 2'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="shippingAddress2" value="<?=  $order ? $order->getCalculatedShippingAddress2() : ''; ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Address Line 3'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="shippingAddress3" value="<?=  $order ? $order->getCalculatedShippingAddress3() : ''; ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('City'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="shippingAddressCity" value="<?=  $order ? $order->getCalculatedShippingAddressCity() : ''; ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('County'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="shippingAddressCounty" value="<?=  $order ? $order->getCalculatedShippingAddressCounty() : ''; ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Postcode'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="shippingAddressPostcode" value="<?=  $order ? $order->getCalculatedShippingAddressPostcode() : ''; ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Country'); ?></span>
                    <?=
                    $this->mustache(
                        'elements/custom-select.mustache',
                        [
                            'holder' => 'order-inputbox-holder',
                            'class' => 'copy-address',
                            'name' => 'shippingAddressCountry',
                            'searchField' => true,
                            'initialValue' => $order ? $order->getCalculatedShippingAddressCountry() : '',
                            'options' => CountrySelect::getDefaultCountryOptions(CountryNameByCode::getCountryNameFromCode($order ? $order->getCalculatedShippingAddressCountry() : '', false)),
                            'disabled' => !$this->editable,
                        ]
                    )
                    ?>
                </label>
            <?php elseif ($order) : ?>
                <fieldset class='inputbox'>
                    <legend><?=$this->translate('eBay Global Shipping');?></legend>
                    <p id='fulfilment-information'><?=
                        ($order && $order->getFulfilmentAddress()->getAddressFullName() ? $order->getFulfilmentAddress()->getAddressFullName() . '<br />' : '') .
                        ($order && $order->getFulfilmentAddress()->getAddressCompanyName() ? $order->getFulfilmentAddress()->getAddressCompanyName() . '<br />' : '') .
                        ($order ? $order->getFulfilmentAddress()->getAddress1() : '') . '<br />' .
                        ($order ? $order->getFulfilmentAddress()->getAddress2() : ''). '<br />' .
                        ($order && $order->getFulfilmentAddress()->getAddress3() ? $order->getFulfilmentAddress()->getAddress3() . '<br />' : '') .
                        ($order && $order->getFulfilmentAddress()->getAddressCity() ? $order->getFulfilmentAddress()->getAddressCity() . '<br />' : '') .
                        ($order && $order->getFulfilmentAddress()->getAddressCounty() ? $order->getFulfilmentAddress()->getAddressCounty() . '<br />' : '') .
                        ($order ? $order->getFulfilmentAddress()->getAddressPostcode() : '') . '<br />' .
                        ($order ? $order->getFulfilmentAddress()->getAddressCountry() : '')
                        ;?></p>
                </fieldset>
            <?php endif; ?>
            <label>
                <span class="inputbox-label"><?= $this->translate('Email'); ?></span>
                <div class="order-inputbox-holder">
                    <input class="inputbox" type="text" name="shippingEmailAddress" value="<?=  $order ? $order->getCalculatedShippingEmailAddress() : ''; ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                </div>
            </label>
            <label>
                <span class="inputbox-label"><?= $this->translate('Telephone'); ?></span>
                <div class="order-inputbox-holder">
                    <input class="inputbox" type="text" name="shippingPhoneNumber" value="<?=  $order ? $order->getCalculatedShippingPhoneNumber() : ''; ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                </div>
            </label>
        </div>
        <?php if ($this->editable && $this->requiresSaveButton): ?>
            <div class="half" style="clear:both; padding-top:0px;">
                <label>
                    <input type="submit" name="save" class="button form-button address-button" value="<?= $this->translate('Save'); ?>">
                </label>
            </div>
        <?php endif; ?>
    </form>
</div>