<?php if(count($linkedOrders)): ?>
    <form class="single-row">
        <label>
            <span class="sprite-linked-29-black"></span>
            <span class="large-heading-left">Linked Orders:</span>
            <div class="linked-orders-list">
                <?php foreach ($linkedOrders as $orderId): ?>
                    <a href="/orders/<?= $orderId ?>" ><?= $orderId ?></a>
                <?php endforeach; ?>
            </div>
        </label>
    </form>
<?php endif; ?>