<div class="order-details">
    <div>
        <span>
            <strong><?= $this->translate('Order ID'); ?>: </strong>
            <?= $orderId; ?>
        </span>
    </div>
    <div>
        <span>
            <strong><?= $this->translate('Buyer'); ?>: </strong>
            <?= $buyerName ?><?php if (isset($buyerUsername)) :?> (<?= $buyerUsername ?>)<?php endif; ?>
            (<a href="<?= $orderUrl ?>">Orders</a> / <a href="<?= $messageUrl ?>">Messages</a>)
        </span>
    </div>
</div>
