<div class="shipping-method">
    <div class="shipping-method-label"><?= $this->translate('Shipping Method'); ?></div>
    <div class="shipping-method-value"><?= $this->shippingMethod; ?></div>
</div>
<?php if (isset($this->labels)) : ?>
<div class="shipping-label-table">
    <span class="grid-table">
        <span class="grid-table-header-row">
            <span class="grid-table-col carrier-col">Carrier</span>
            <span class="grid-table-col carrier-service-col">Service</span>
            <span class="grid-table-col deliver-instruction-col">Delivery Instruction</span>
            <span class="grid-table-col parcels-col">Parcel</span>
            <span class="grid-table-col weight-col">Weight</span>
            <span class="grid-table-col tracking-no-col">Tracking Number</span>
            <span class="grid-table-col action-col">Action</span>
        </span>
            <?php foreach ($this->labels as $label) : ?>
            <span class="grid-table-row">
                <span class="grid-table-col carrier-col"><img src=<?= $this->basePath().CG_UI\Module::PUBLIC_FOLDER.'img/logos/'.$this->imageSource ?> /></span>
                <span class="grid-table-col carrier-service-col"><?= $label['courierService'] ?></span>
                <span class="grid-table-col deliver-instruction-col"><?= $label['deliveryInstructions'] ?: 'None' ?></span>
                <span class="grid-table-col col-split parcels-col">
                    <?php foreach ($label['parcels'] as $parcel){ echo "<span>".(isset($parcel['number'])?$parcel['number']:'')."</span>"; } ?>
                </span>
                <span class="grid-table-col col-split weight-col">
                    <?php foreach ($label['parcels'] as $parcel){ echo "<span>".(isset($parcel['weight'])?$parcel['weight']:'')."</span>"; } ?>
                </span>
                <span class="grid-table-col tracking-no-col">
                    <?= ($tracking) ? $tracking->getNumber() : ""; ?>
                </span>
                <span class="grid-table-col action-col">
                    <button class="button form-button tracking-button">Print</button>
                    <button class="button form-button tracking-button">Cancel</button>
                </span>
            </span>
            <?php endforeach; ?>
    </span>
</div>
<?php endif; ?>