<div id="setup-wizard-payment-footer">
    <div class="details">
        <div>30-day rolling contract. Cancel any time.</div>
        <div class="limits">Exceeding your package limits will move you onto the next package automatically and the difference will be charged.</div>
    </div>
    <div>
        <?= $this->mustache('elements/buttons.mustache', ['buttons' => $this->buttons]) ?>
    </div>
</div>