<div id="setup-wizard-payment">
    <div class="half">
        <div id="setup-wizard-package-selector" class="clearfix">
            <div id="package-setup"></div>
        </div>
        <?= $this->promoCode; ?>
        <div id="setup-wizard-payment-selector" class="clearfix">
            <div><?= $this->paymentMethodSelect ?? '' ?></div>
            <div class="payment-setup"><?= $this->paymentMethod ?? '' ?></div>
        </div>
    </div>
    <div id="demo" class="half">
        <div class="demo-info">
            <div>Beat your competitors.<br />See the full system first.</div>
            <div class="demo-link">
                <a target="_blank" href="<?= $this->demoLink ?>">WATCH A DEMO NOW</a>
            </div>
            <div class="callUs">Or call us on <?= $this->phoneNumber ?></div>
        </div>
    </div>
</div>
<script type="text/javascript">
    require.config({
        paths: {
            'Common': '<?= $this->basePath() ?>/cg-built/vendor/cg-common/dist/js/Common',
            'SetupWizard': '<?= $this->basePath() . SetupWizard\Module::PUBLIC_FOLDER ?>js'
        }
    });

    require([
        '<?= SetupWizard\Module::PUBLIC_FOLDER ?>js/steps/Payment.js',
        'react',
        'react-dom',
        'SetupWizard/Component/Payment/PackageSelector',
        'SetupWizard/Payment/Locale/<?= $this->locale ?>',
        '<?= $this->basePath() . CG_Billing\Module::PUBLIC_FOLDER . 'js/Package/PromoCode.js'; ?>',
    ], function(Payment, React, ReactDOM, PackageSelectorComponent, Locale, PromoCode) {
        PromoCode.URL_APPLY_CODE = '/setup/payment/applyDiscountCode';
        PromoCode.init();
        var paymentSelector = document.getElementById('setup-wizard-payment-selector');
        paymentSelector.style.display = (<?= json_encode($this->selectedPackage) ?> ? "inherit": "none");
        var payment = new Payment(n, <?= json_encode($this->selectedPackage) ?>, <?= json_encode($this->selectedBillingDuration) ?>, "<?= $this->activePaymentMethod ?>");
        ReactDOM.render(
            React.createElement(PackageSelectorComponent, {
                locale: new Locale(),
                phoneNumber: <?= json_encode($this->phoneNumber) ?>,
                selectedPackage: <?= json_encode($this->selectedPackage) ?>,
                selectedBillingDuration: <?= json_encode($this->selectedBillingDuration) ?>,
                packages: <?= json_encode($this->packages) ?>,
                onPackageSelection: function(packageId) {
                    paymentSelector.style.display = (packageId ? "inherit": "none");
                    payment.setSelectedPackage(packageId);
                },
                onBillingDurationSelection: function(billingDuration) {
                    payment.setSelectedBillingDuration(billingDuration);
                }
            }),
            document.getElementById('package-setup')
        );
        <?php if ($this->takePayment) : ?>$(document).ready(payment.takePayment.bind(payment));<?php endif ?>
    });
</script>