<div id="setup-wizard-payment">
    <div id="setup-wizard-package-selector">
        <div id="package-setup" class="half"></div>
        <div class="half demo">
            <div class="demo-info">
                <div>Beat your competitors.<br />See the full system first.</div>
                <div class="demo-link">
                    <a target="_blank" href="https://samgilbert.youcanbook.me/">WATCH A DEMO NOW</a>
                </div>
                <div class="callUs">Or call us on 01617110248</div>
            </div>
        </div>
    </div>
    <div id="setup-wizard-payment-selector">
        <div><?= $this->paymentMethod ?></div>
        <div class="half payment-setup"></div>
    </div>
</div>
<script type="text/javascript">
    require.config({
        paths: {
            'Common': '<?= $this->basePath() ?>/cg-built/common/js/Common',
            'SetupWizard': '<?= $this->basePath() . SetupWizard\Module::PUBLIC_FOLDER ?>js'
        }
    });

    require([
        '<?= SetupWizard\Module::PUBLIC_FOLDER ?>js/steps/Payment.js',
        'react',
        'react-dom',
        'SetupWizard/Component/Payment/PackageSelector'
    ], function(Payment, React, ReactDOM, PackageSelectorComponent) {
        var payment = new Payment(n, <?= json_encode($this->selectedPackage) ?>, "<?= $this->activePaymentMethod ?>");
        ReactDOM.render(
            React.createElement(PackageSelectorComponent, {
                selectedPackage: <?= json_encode($this->selectedPackage) ?>,
                packages: <?= json_encode($this->packages) ?>,
                onPackageSelection: function(packageId) {
                    var paymentSelector = document.getElementById('setup-wizard-payment-selector');
                    paymentSelector.style.display = (packageId ? "inherit": "none");
                    payment.setSelectedPackage(packageId);
                }
            }),
            document.getElementById('package-setup')
        );
    });
</script>