<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'NewRelic\Api\Event\RegisterBrowserTimings' => __DIR__ . '/../../module/NewRelic/src/NewRelic/Api/Event/RegisterBrowserTimings.php',
  'NewRelic\Api\Event\RegisterController'     => __DIR__ . '/../../module/NewRelic/src/NewRelic/Api/Event/RegisterController.php',
  'NewRelic\Api\Event\RegisterRoute'          => __DIR__ . '/../../module/NewRelic/src/NewRelic/Api/Event/RegisterRoute.php',
  'NewRelic\Api\Event\RegisterUser'           => __DIR__ . '/../../module/NewRelic/src/NewRelic/Api/Event/RegisterUser.php',
  'NewRelic\Module'                           => __DIR__ . '/../../module/NewRelic/Module.php',
  'attach'                                    => __DIR__ . '/../../module/NewRelic/Module.php',
  'interface_exists'                          => __DIR__ . '/../../module/NewRelic/Module.php',
  'getConfig'                                 => __DIR__ . '/../../module/NewRelic/Module.php',
  'Application\Controller\IndexController'    => __DIR__ . '/../../module/Application/src/Application/Controller/IndexController.php',
  'Application\Forms\Factory'                 => __DIR__ . '/../../module/Application/src/Application/Forms/Factory.php',
  'Application\Module'                        => __DIR__ . '/../../module/Application/Module.php',
);
