<?php
/*
 * This file is generated but should still be committed
 */
return array(
    'alexandresalome_php-selenium_src_Selenium',
    'behat_mink-browserkit-driver_src_Behat_Mink_Driver',
    'behat_mink-goutte-driver_src_Behat_Mink_Driver',
    'behat_mink-selenium-driver_src_Behat_Mink_Driver',
    'behat_mink-selenium2-driver_src_Behat_Mink_Driver',
    'behat_mink-zombie-driver_src_Behat_Mink_Driver',
    'behat_mink_src_Behat_Mink',
    'channelgrabber_cache_CG_Cache',
//    'channelgrabber_codeception_CG_Codeception',
    'channelgrabber_constants_CG',
    'channelgrabber_etag_CG_ETag',
    'channelgrabber_guzzle_CG_Guzzle',
    'channelgrabber_http_CG_Http',
    'channelgrabber_log_CG',
    'channelgrabber_predis_CG_Predis',
    'channelgrabber_redis_CG_Redis',
//    'channelgrabber_slim_CG_Slim',
    'channelgrabber_sso_CG_Sso',
    'channelgrabber_stdlib_CG_Stdlib',
//    'channelgrabber_ui_CG_UI',
    'channelgrabber_user_CG',
    'channelgrabber_validation_CG_Validation',
    'channelgrabber_zf2-hal_CG_Zend_Hal',
//    'channelgrabber_zf2-installer_CG_Zend_Installer',
    'channelgrabber_zf2-logclient_src_CG\_Log',
    'channelgrabber_zf2-login_src_CG\_Login',
    'channelgrabber_zf2-register_src_CG\_Register',
    'channelgrabber_zf2-ssoclient_src_CG\_SSO',
    'channelgrabber_zf2-stdlib_CG_Zend_Stdlib',
//    'channelgrabber_zf2-v4-ui_src_CG\_UI',
    'codeception_codeception_src_Codeception',
    'davedevelopment_phpmig_src_Phpmig',
    'fabpot_goutte_Goutte',
    'guzzle_guzzle_src_Guzzle',
    'instaclick_php-webdriver_lib_WebDriver',
    'monolog_monolog_src_Monolog',
    'nocarrier_hal_src_Nocarrier',
    'phpspec_php-diff_lib_Diff',
//    'phpspec_phpspec_src_PhpSpec',
    'phpspec_prophecy_src_Prophecy',
//    'pimple_pimple_lib_Pimple',
    'predis_predis_lib_Predis',
    'psr_log_Psr_Log',
    'symfony_browser-kit_Symfony_Component_BrowserKit',
    'symfony_class-loader_Symfony_Component_ClassLoader',
//    'symfony_config_Symfony_Component_Config',
    'symfony_console_Symfony_Component_Console',
    'symfony_css-selector_Symfony_Component_CssSelector',
    'symfony_dom-crawler_Symfony_Component_DomCrawler',
    'symfony_event-dispatcher_Symfony_Component_EventDispatcher',
    'symfony_filesystem_Symfony_Component_Filesystem',
    'symfony_finder_Symfony_Component_Finder',
    'symfony_process_Symfony_Component_Process',
    'symfony_yaml_Symfony_Component_Yaml',
    'videlalvaro_php-amqplib_PhpAmqpLib',
//    'zendframework_zendframework_library_Zend',
);