<div style="margin: 5px;">
    Before using this feature please familiarise yourself with our best practices guides for importing listings below:
</div>
<div style="margin: 5px;">
    <a target="_blank" href="http://guide.cloudcommercegroup.com/products-and-stock/how-to-import-products-into-channelgrabber">
        Importing Listings - Important Information
    </a>
</div>
<div style="margin: 5px;">
    ChannelGrabber recommends manually importing listings from the channel which has the most accurate stock level first.
    Using this feature on more than one account at a time by-passes that recommendation.
</div>
<div style="margin: 5px;">
    You should not use this feature if your product SKUs are not 100% accurate as this will lead to stock errors and potential oversells.
</div>
<div style="margin: 5px;">
    <a target="_blank" href="http://guide.cloudcommercegroup.com/products-and-stock/understanding-skus">
        Understanding SKU's
    </a>
</div>
<div style="margin: 5px;">
    Please click Confirm below to <?= $this->translate('confirm') ?> that you have read the above message and recommended guides, and are aware of the risks of not using this feature correctly.
</div>