<?php $this->headLink()->appendStylesheet($this->basePath() .'/cg-built/vendor/cg-common/dist/css/default.css', ['screen', 'print']) ?>

<?php $this->inlineScript()->captureStart(); ?>
require.config({
    paths: {
        'StockTemplates': '<?= $this->basePath() . DataExchange\Module::PUBLIC_FOLDER; ?>/js/DataExchange/StockTemplates',
        'Common': '<?= $this->basePath() ?>/cg-built/vendor/cg-common/dist/js/Common'
    }
});
$(document).ready(function() {
    const rootNode = document.getElementById('stock-templates-root');
    require([
        "StockTemplates/Index",
    ],
    function(
        StockTemplatesIndex
    ) {
        new StockTemplatesIndex(
            rootNode,
            <?= json_encode($this->templates) ?>,
            <?= json_encode($this->cgFieldOptions) ?>
        );
    });
});
<?php $this->inlineScript()->captureEnd(); ?>

<div id="breadcrumbs" class="floatLeftClear">
    <h2 class="heading-large">
        Stock Templates
    </h2>
</div>
<div class="module clearfix">
    <div id="stock-templates-root" class="u-clear-both u-margin-top-med"></div>
</div>