<div class="channelgrabber-logo" style="width: 216px; height: 226px">
    <div class="ekm-registration-ekm-logo" style="width: 175px; height: 175px; margin-left: -87px; position: relative; left: 50%">
        <img style="display: block; width: 175px; height: 175px; float: left; background: #FEFEFE; border-radius: 10px" src="/channelgrabber/setup-wizard/img/channel-badges/ekm.png">
    </div>
    <div class="ekm-registration-channelgrabber-logo" style="width: 216px; height: 16px; margin-top: 20px">
        <span  style="display: block; float: left; width: 70px; margin: 0 10px 0 0; color: #FEFEFE">Powered by</span><img style="display: block; width: 136px; height: 16px; float: left;" src="/channelgrabber/zf2-v4-ui/img/channelgrabber-logo-white.png">
    </div>
</div>