let elementTypes = {
    INPUT_SAFE_SUBMITS: 'INPUT_SAFE_SUBMITS',
    SELECT_DROPDOWN: 'SELECT_DROPDOWN',
    SELECT_VAT_DROPDOWN: 'SELECT_VAT_DROPDOWN',
    STOCK_MODE_SELECT_DROPDOWN: 'STOCK_MODE_SELECT_DROPDOWN',
    DIMENSIONS_INPUT_SUBMITS: 'DIMENSIONS_INPUT_SUBMITS',
    LOW_STOCK_SELECT_DROPDOWN: 'LOW_STOCK_SELECT_DROPDOWN',
    INCLUDE_PURCHASE_ORDERS_IN_AVAILABLE_SELECT_DROPDOWN: 'INCLUDE_PURCHASE_ORDERS_IN_AVAILABLE_SELECT_DROPDOWN',
};

export default elementTypes;