<?php $this->inlineScript()->captureStart(); ?>
require.config({
    paths: {
        ColumnPicker: "<?= $this->baseUrl . Orders\Module::PUBLIC_FOLDER . 'js/columnPicker' ?>"
    }
});
require(
    ["ColumnPicker"],
    function(ColumnPicker) {
        var templateUrl = '<?= $this->basePath() . Orders\Module::PUBLIC_FOLDER . 'template/columnPicker.html' ?>';
        var templateRowId = 'column-picker';
        CGMustache.get().fetchTemplate(templateUrl, function(template, cgmustache)
        {
            var html = cgmustache.renderTemplate(template, [], templateRowId);
            $('#order-table-options').after(html);
            var columnPicker = new ColumnPicker($('#column-picker-dropdown'));
            $('#order-table-options').click(function()
            {
                columnPicker.toggle();
            });
        });
    }
);
<?php $this->inlineScript()->captureEnd(); ?>

<span class="icon-med cog" id="order-table-options">Options</span>