<div class="module filter-module clearfix navbar-content">
    <h3><?= $this->translate('Saved Filters') ?></h3>
    <div class="module-content nav">
        <ul id="savedFilters">
            <li class='empty-list<?= count($filters) ? ' hidden' : '' ?>'><?= $this->translate('No saved filters') ?></li>
            <?php if (count($filters)) : ?>
                <?= $this->mustacheLoop('elements/savedFilter.mustache', $filters) ?>
            <?php endif; ?>
        </ul>
    </div>
</div>