<?php $this->inlineScript()->captureStart(); ?>
require.config({
    paths: {
        storedFilters: "<?= Orders\Module::PUBLIC_FOLDER ?>js/storedFilters"
    }
});
require([
    'storedFilters'
],
function(StoredFilters) {
    var storedFilters = new StoredFilters("#filters", "#savedFilters");
    storedFilters.bindSaveTo(
        storedFilters.getFilters().find("[data-action='save-filters']")
    );
});
<?php $this->inlineScript()->captureEnd(); ?>
<div class="module filter-module clearfix navbar-content">
    <h3><?= $this->translate('Saved Filters') ?></h3>
    <div class="module-content nav">
        <ul id="savedFilters" data-template="<?= Orders\Module::PUBLIC_FOLDER ?>template/popup/saveFilter.mustache">
            <li class='empty-list<?= count($filters) ? ' hidden' : '' ?>'><?= $this->translate('No saved filters') ?></li>
            <?php if (count($filters)) : ?>
                <?= $this->mustacheLoop('elements/savedFilter.mustache', $filters) ?>
            <?php endif; ?>
        </ul>
    </div>
</div>