<?php $this->inlineScript()->captureStart(); ?>
var $body = $('html, body');
var headerHeight = $('#fixed-header').height() + $('#sub-header').height();
$('a').click(function() {
  var href = $.attr(this, 'href');
  $body.animate({
    scrollTop: $( $.attr(this, 'href') ).offset().top - headerHeight
  }, 200,  function () {
     window.location.hash = href;
  });
  return false;
});
<?php $this->inlineScript()->captureEnd(); ?>
<h2>Sections</h2>
<ul>
<?php foreach($this->links as $link): ?>
    <li><a href="#<?= $link ?>"><?= ucwords(implode(" ", preg_split("/(?=[A-Z])/", $link))); ?></a></li> <!-- TODO use translator here -->
<?php endforeach;?>
</ul>