<?php $this->inlineScript()->captureStart(); ?>
require.config({
    paths: {
        filters: "<?= Orders\Module::PUBLIC_FOLDER ?>js/filters",
        storedFilters: "<?= Orders\Module::PUBLIC_FOLDER ?>js/filters/stored"
    }
});
require([
    'storedFilters'
],
function(StoredFilters) {
    var storedFilters = new StoredFilters(n, "#filters", "#savedFilters");
    storedFilters.bindSaveTo(
        storedFilters.getFilters().find("[data-action='save-filters']")
    );
});
<?php $this->inlineScript()->captureEnd(); ?>
<div class="filter-module clearfix navbar-content">
    <ul class="module-content nav">
        <li>
            <span class="heading-medium"><?= $this->translate('Saved Filters') ?></span>
            <div class="u-float-left u-margin-left-small" style="display: <?= count($filters) > 5  ? 'block' : 'none'?>">
                <input id="saved-filters-search" type="text" class="inputbox" placeholder="search"/>
            </div>
            <ul
                id="savedFilters"
                style="display:none;"
                data-save="<?= $this->url('Orders/' . Orders\Controller\StoredFiltersController::ROUTE_SAVE) ?>"
                data-remove="<?= $this->url('Orders/' . Orders\Controller\StoredFiltersController::ROUTE_REMOVE) ?>"
                data-template="<?= Orders\Module::PUBLIC_FOLDER ?>template/elements/savedFilter.mustache"
                data-popup="<?= Orders\Module::PUBLIC_FOLDER ?>template/popup/saveFilter.mustache"
                >
                <li class='empty-list<?= count($filters) ? ' hidden' : '' ?>'><?= $this->translate('No saved filters') ?></li>
                <?php if (count($filters)) : ?>
                    <?= $this->mustacheLoop('elements/savedFilter.mustache', $filters) ?>
                <?php endif; ?>
            </ul>
        </li>
    </ul>
</div>
