<span class="bulk-action-seperator"></span>
<?= $refreshButton; ?>
<div class="hide-filters double-arrow vertical up" data-target="body" data-toggle-class="headerbar-hidden"
     data-preference-key="<?= Products\Listing\Service::LISTING_FILTER_BAR_STATE_KEY; ?>"
     data-preference-show="<?= $this->translate('Show Filters'); ?>"
     data-preference-hide="<?= $this->translate('Hide Filters'); ?>">
    <?= $isHeaderBarVisible ? $this->translate('Hide Filters') : $this->translate('Show Filters'); ?>
</div>
