<?php $this->headLink()->appendStylesheet($this->basePath() . CG_UI\Module::PUBLIC_FOLDER . 'css/common/subheader-hide.css'); ?>
<div id="breadcrumbs" class="floatLeftClear">
    <span class="heading-large"><?= $this->translate('API Credentials'); ?>
</div>
<div class="module clearfix">
    <?php if ($this->allowed) {
        echo $this->partial('settings/api/details/credentials.phtml', compact('credentialsKey', 'credentialsSecret'));
    } else {
        echo $this->partial('settings/api/details/upgradeNotice.phtml', compact('message', 'url'));
    } ?>
</div>