<?php $this->inlineScript()->captureStart(); ?>
require.config({
    paths: {
        'Stock': '<?= $this->basePath() . Products\Module::PUBLIC_FOLDER; ?>/js/Stock',
        'Product': '<?= $this->basePath() . Products\Module::PUBLIC_FOLDER; ?>/js/Product',
        'Variation': '<?= $this->basePath() . Products\Module::PUBLIC_FOLDER; ?>/js/Variation',
        'Details': '<?= $this->basePath() . Products\Module::PUBLIC_FOLDER; ?>/js/Details',
        'Common': '<?= $this->basePath() ?>/cg-built/vendor/cg-common/dist/js/Common',
        'CategoryMapper': '<?= $this->basePath() . Products\Module::PUBLIC_FOLDER; ?>js/CategoryMapper'
    }
});
require([
    'Product/Product',
    'Clipboard',
    'Common/Utils/Image'
],
function(ProductRoot, Clipboard, ImageUtils) {
    var utilities = {
        image: new ImageUtils({ imageBasePath: '<?= $this->basePath() . Products\Module::PUBLIC_FOLDER; ?>img' })
    };
    var searchAvailable = document.getElementById('searchBoxMount');
    var productRoot = new ProductRoot(
        document.getElementById('products-mount-node'),
        utilities,
        searchAvailable,
        <?=  ($listingCreationAllowed ? 'true' : 'false') ?>,
        '<?= $managePackageUrl; ?>',
        <?= ($isAdmin ? 'true' : 'false') ?>,
        '<?= $searchTerm ?>',
        <?= $featureFlagJson; ?>,
        '<?= $this->remoteUrl('/company', 'admin'); ?>',
        <?= json_encode($taxRates); ?>,
        <?= json_encode($stockModeOptions) ?>,
        <?= json_encode($incPOStockInAvailableOptions) ?>,
        <?= json_encode($ebaySiteOptions); ?>,
        <?= json_encode($categoryTemplateOptions); ?>,
        <?= json_encode($conditionOptions); ?>,
        '<?= $defaultCurrency; ?>',
        '<?= $salesPhoneNumber; ?>',
        '<?= $demoLink; ?>',
        <?= ($showVAT ? 'true' : 'false') ?>,
        '<?= $massUnit; ?>',
        '<?= $lengthUnit; ?>',
        <?= json_encode($this->pickLocations) ?>,
        <?= json_encode($this->pickLocationValues) ?>
    );
});
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->placeholder('#main.class')->append('full-width'); ?>
<?php
$this->placeholder('#sidebar')
    ->append($this->sidebarLinks);
?>

<?php
$this->headLink()->appendStylesheet($this->basePath() .'/cg-built/vendor/cg-common/dist/css/default.css', ['screen', 'print']);
$this->headLink()->appendStylesheet($this->basePath() .'/cg-built/vendor/fixed-data-table-2/dist/fixed-data-table.css', ['screen', 'print']);
?>

<link href="http://fonts.googleapis.com/css?family=Lato:400,700" media="screen" rel="stylesheet" type="text/css">

<div id="main" class="products transition-preload module clearfix<?= $this->placeholder('#main.class')->setPrefix(' ')->setIndent(1) ?>">
<?= $this->breadcrumbs; ?>
<?= $this->bulkItems; ?>
    <div id="products-mount-node">
    </div>

    <div id='products-loading-message' class='dataTables_processing u-ease_1-25'>
        <span class="u-flex-center">
                <div class="indicator-sizer -default u-margin-right-small">
                    <?=
                        $this->mustache(
                            'elements/loadingIndicator.mustache'
                        )
                    ?>
                </div>

                <div>Loading products...</div>
        </span>
    </div>

    <div id="account-stock-settings-table-container" style="display:none">
        <?=$this->accountStockSettingsTableView;?>
    </div>
</div>
<style>
/**
  This is a hack to hide the sidebar away for now TODO: Remove this
  When introducing filters (ie Saved Filters)
**/
#main-wrapper {
    margin-left:0px;
    width:100%;
}
</style>
