<?php $this->inlineScript()->captureStart(); ?>
require([
"showHideFilters"
],
function(showHideFilters) {
var productPage = new showHideFilters();
});
require.config({
    paths: {
        'Stock': '<?=$this->basePath() . Products\Module::PUBLIC_FOLDER; ?>/js/Stock'
    }
});
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->headScript()->appendFile($this->basePath() . CG_UI\Module::PUBLIC_FOLDER . 'js/mustache.js'); ?>
<?php $this->headScript()->appendFile($this->basePath() . CG_UI\Module::PUBLIC_FOLDER . 'js/cg-mustache.js'); ?>
<?php $this->placeholder('#main.class')->append('full-width'); ?>
<?php
$this->placeholder('#sidebar')
    ->append($this->sidebarLinks);
?>
<?php $this->headLink()->appendStylesheet($this->basePath() . Orders\Module::PUBLIC_FOLDER . 'css/orders.css') ?>
<div id="main" class="transition-preload module clearfix<?= $this->placeholder('#main.class')->setPrefix(' ')->setIndent(1) ?>">
<?= $this->breadcrumbs; ?>
<?= $this->bulkItems; ?>
    <div id="products-list">
        <?= $this->products; ?>
    </div>
</div>
