<div class="setup-wizard-account-badges">
    <?=$this->channelBadges;?>
</div>
<div class="fixed-notifications">
    <div class='notifications'>
        <div class="success clearfix">
            <span class="icon"><span>&tick;</span></span><span class="content">Tap a channel to create a link between that service and OrderHub.</span>
        </div>
    </div>
</div>
<script type="text/javascript">
    require(['<?=SetupWizard\Module::PUBLIC_FOLDER;?>js/steps/Channels/Pick.js'], function(Pick)
    {
        new Pick(n, '<?=$this->addUri;?>');
    });
</script>