<div id="breadcrumbs" class="floatLeftClear">
    <span class="heading-large"><?= $this->translate('Create Listings from Import'); ?>
</div>
<div class="module clearfix">
    <form id="listing-import-form" method="POST" action="<?=$this->saveUri;?>">
        <div class="half">
            <label>
                <span class="inputbox-label"><?= $this->translate('Account to import to');?>:</span>
                <div class="order-inputbox-holder">
                    <?=$this->accountSelect;?>
                </div>
            </label>
            <?=$this->fileUpload;?>
            <div class="order-inputbox-holder">
                <?=$this->importButton;?>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    $(document).ready(function()
    {
        require(['<?=$this->basePath() . Settings\Module::PUBLIC_FOLDER . 'js/CreateListings/Service.js';?>'], function(Service)
        {
            new Service(n);
        });
    });
</script>