<?php $this->placeholder('#content.style')->append('margin-top: 199px;'); ?>
<?php $this->headScript()->appendFile($this->basePath() . '/channelgrabber/zf2-v4-ui/js/order.js'); ?>
<?php $this->inlineScript()->captureStart(); ?>
$(function() {
    $("#filters #filter-btn").click(function() {
        applyFilter();
    });
});
<?php $this->inlineScript()->captureEnd(); ?>
<div id="filters">
    <div class="row">
        <div class="date-range filter clearfix">
            <label for="date-range">Date Range</label>
            <input name="date-range" class="date-range-input" value=""/>
            <span class="toggle icon-med inverted calendar">&nbsp;</span>
            <input type="hidden" name="date-range-from" class="date-range-input-from" value="<?= $filter->getTimeFrom() ?>" />
            <input type="hidden" name="date-range-to" class="date-range-input-to" value="<?= $filter->getTimeTo() ?>" />
            <div class="date-range-menu">
                <ul>
                    <?php
                    $dateRanges = [];
                    $dateRanges[] = [
                        'title' => 'All Time',
                        'from'  => '',
                        'to'    => ''
                    ];
                    $dateRanges[] = [
                        'title' => 'Today',
                        'from'  => time(),
                        'to'    => time()
                    ];
                    $dateRanges[] = [
                        'title' => 'Last 7 days',
                        'from'  => strtotime("-7 days"),
                        'to'    => time()
                    ];
                    $dateRanges[] = [
                        'title' => 'Month to date',
                        'from'  => strtotime( 'first day of ' . date( 'F Y')),
                        'to'    => time()
                    ];
                    $dateRanges[] = [
                        'title' => 'Year to date',
                        'from'  => strtotime( 'first day of January ' . date('Y')),
                        'to'    => time()
                    ];
                    $dateRanges[] = [
                        'title' => 'The previous month',
                        'from'  => strtotime( 'first day of last month '),
                        'to' => strtotime( 'last day of last month '),
                    ]; ?>
                    <?php foreach($dateRanges as $dateRange):?>
                        <li class="date-range-option"><a href="#" data-range-from="<?php if(!empty($dateRange['from'])): echo date('d/m/Y', $dateRange['from']); else: echo ("All"); endif; ?>" <?php if(!empty($dateRange['to'])):?>data-range-to="<?=date('d/m/Y', $dateRange['to']);?><?php endif; ?>"><?=$dateRange['title']?></a></li>
                    <?php endforeach;?>
                    <!-- <li class="date-range-option with-calendar">
                        <a href="#" class="date-range-option">Specific Date <span class="arrow right"></span></a>
                        <div class="date-range-calendar">
                            <div class="datepicker"></div>
                        </div>
                    </li> -->
                    <li class="date-range-option with-calendar">
                        <a href="#" class="date-range-option">Date Range <span class="arrow right"></span></a>
                        <div class="date-range-calendar">
                            <div class="datepicker from"></div>
                            <div class="datepicker to"></div>
                            <div class="buttons">
                                <span class="button close">Apply</span>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div class="filter clearfix">
            <label for="contains-text">Contains Text</label>
            <input name="contains-text" type="text" placeholder="Contains text..." class="" value="<?= $filter->getSearchTerm() ?>"/>
        </div>
        <div class="filter clearfix">
            <label>Status:</label>
            <div class="custom-select">
                <div class="selected">Select <span class="arrow down">&nbsp;</span></div>
                <ul>
                    <li><a href="#">New</a></li>
                    <li><a href="#">Processing</a></li>
                    <li><a href="#">Dispatched</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="filter clearfix">
            <label>Include Country:</label>
            <div class="custom-select custom-select-group custom-select-concatenate large hover-no-scroll">
                <div class="selected">
                    <span class="selected-content">Select</span>
                    <span class="arrow down">&nbsp;</span>
                </div>

                <div class="open-content">
                    <div class="search-selected-wrapper clearfix">
                        <input class="search-selected" type="text" placeholder="Search..." value=""/>
                        <span class="icon-med inverted search">Search</span>
                    </div>
                    <div class="custom-select-actions">
                        <a class="select-all">Select All</a> | <a class="clear-action">Clear</a>
                    </div>
                    <ul>
                        <?php
                        $options = ['UK','Austria','Croatia','Cyprus','France','Germany','Italy','Spain'];
                        foreach($options as $option):
                            ?>
                            <li><a href="javascript:void(0);" class="custom-select-item" title="<?=$option?>"><input type="checkbox"  /> <?=$option?></a></li>
                        <? endforeach; ?>
                        <li><a class="no-results hidden">No results</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="filter clearfix">
            <label>Columns:</label>
            <div class="custom-select custom-select-group custom-select-grouped large hover-no-scroll">
                <div class="selected">
                    <span class="selected-content">Select</span>
                    <span class="arrow down">&nbsp;</span>
                </div>
                <div class="open-content">
                    <div class="search-selected-wrapper clearfix">
                        <input class="search-selected" type="text" placeholder="Search..." value=""/>
                        <span class="icon-med inverted search">Search</span>
                    </div>
                    <div class="custom-select-actions">
                        <a class="select-all">Select All</a> | <a class="clear-action">Clear</a>
                    </div>
                    <?php
                    $selectedOptions = ['Account', 'Batch', 'Buyer', 'Channel','Dispatch','Messages','Order ID / Product Information', 'Order Date','Print','Shipping Method', 'Status', 'Total'];
                    $options = ['Comments', 'Kashflow', 'Notes', 'Tax','Tax Rate'];
                    ?>
                    <div class="custom-select-scroll">
                        <?php if(!empty($selectedOptions)):?>
                            <ul class="active">
                                <?php foreach($selectedOptions as $option): ?>
                                    <li><a href="javascript:void(0);" class="custom-select-item active" title="<?=$option?>"><input type="checkbox" checked="checked"/> <?=$option?></a></li>
                                <? endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php if(!empty($options)):?>
                            <ul>
                                <? foreach($options as $option): ?>
                                    <li><a href="javascript:void(0);" class="custom-select-item" title="<?=$option?>"><input type="checkbox"  /> <?=$option?></a></li>
                                <? endforeach; ?>
                                <li><a class="no-results hidden">No results</a></li>
                            </ul>
                        <?php endif;?>
                    </div>
                </div>
            </div>
        </div>
        <div class="filter">
            <label>&nbsp;</label>
            <input type="button" class="button" value="Apply Filters" name="filter" id="filter-btn" />
        </div>
    </div>
</div>