<?php $this->inlineScript()->captureStart(); ?>
$("#datatable").on("fnServerData", function(event, sSource, aoData, fnCallback, oSettings) {
    $("#filters input[name], #filters select[name]").each(function() {
        aoData.push({"name": "filter[" + $(this).attr("name") + "]", "value": $(this).val()});
    });
});

$("#filters input[name='apply-filters']").on("click", function() {
    $("#datatable").cgDataTable("redraw");
});

$("#filters input[name='clear-filters']").on("click", function() {
    $("#filters input[name][type!='button'], #filters select[name]").val(undefined);
    $("#datatable").cgDataTable("redraw");
});

var templateUrl = '<?= $this->basePath() . Orders\Module::PUBLIC_FOLDER . 'template/row.html' ?>';
var templateRowId = 'order-row';
var formatters = {
    'formatAdditionalOrderItems': function(aData) {
        return function()
        {
            return function(variable, render) {
                aData.extraItems = JSON.parse(JSON.stringify(aData.items));
                aData.extraItems.splice(0, 1);
                return render(variable);
            };
        };
    }
};
CGMustache.get().setupTemplateForDatatableRows(templateUrl, templateRowId, formatters);
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->headScript()->appendFile($this->basePath() . CG_UI\Module::PUBLIC_FOLDER . 'js/mustache.js'); ?>
<?php $this->headScript()->appendFile($this->basePath() . CG_UI\Module::PUBLIC_FOLDER . 'js/cg-mustache.js'); ?>
<?php $this->placeholder('#main.class')->append('full-width'); ?>
<?php $this->placeholder('#sub-header')->append($this->filters); ?>
<?php $this->placeholder('#sidebar')->set($this->sidebar); ?>
<?= $this->bulkItems; ?>
<?= $this->ordersTable; ?>