<?php $this->inlineScript()->captureStart(); ?>
$("#datatable").on("fnServerData", function(event, sSource, aoData, fnCallback, oSettings) {
    $("#filters input[name], #filters select[name]").each(function() {
        var value = $.trim($(this).val());
        if (!value.length) {
            return;
        }
        var name = $(this).attr("name");
        var postName = "filter[" + name + "]";
        if (name.match(/\[\]$/)) {
            var postName = "filter[" + name.replace(/[\[\]]/g, '') + "][]";
        }

        aoData.push({"name": postName, "value": value});
    });
    aoData.push({"name": "filter[batch]", "value": $('#hidden_batch_filter').val()});
});

$("#filters").on("apply", function() {
    $("#datatable").cgDataTable("redraw");
}).on("reset", function() {
    $("#filters :input").not(":button").val(undefined);
    $("#filters :checkbox").prop("checked", false);
    $("#filters .custom-select .selected-content").html("Select");
});

$("#filters input[name='apply-filters']").on("click", function() {
    $("#filters").trigger("apply");
});

$("#filters input[name='clear-filters']").on("click", function() {
    $("#filters").trigger("reset");
    $('#hidden_batch_filter').val("");
    $("#filters").trigger("apply");
});

function batchFilter(batchId) {
    $("#filters").trigger("reset");
    $('#hidden_batch_filter').val(batchId);
    $("#filters").trigger("apply");
}

function clearFilters() {
    $("#filters").trigger("reset");
}

$(document).on('click', '.batch-filter', function(e) {
    e.preventDefault();
    batchFilter($(this).attr('data-name'));
    return false;
});

$("#datatable").on("fnRowCallback", function(event, nRow, aData, iDisplayIndex, iDisplayIndexFull) {
    $("a.title", nRow).cgPjax();
});

require([
    "preference/Preference",
    "slideableSidebar",
    "order/OrderPage"
],
function(Preference, SlideableSidebar, OrderPage) {
    //References to n need to be migrated, it is the notification library
    var preference = new Preference(n);
    var slideableSidebar = new SlideableSidebar();
    var orderPage = new OrderPage(preference, slideableSidebar);
});
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->headScript()->appendFile($this->basePath() . CG_UI\Module::PUBLIC_FOLDER . 'js/mustache.js'); ?>
<?php $this->headScript()->appendFile($this->basePath() . CG_UI\Module::PUBLIC_FOLDER . 'js/cg-mustache.js'); ?>
<?php $this->headScript()->appendFile($this->basePath() . CG_UI\Module::PUBLIC_FOLDER . 'js/jquery/cg-pjax.js'); ?>
<?php $this->placeholder('#main.class')->append('full-width'); ?>
<?php $this->placeholder('#sub-header')->append($filters); ?>
<?php
$this->placeholder('#sidebar')
    ->append($this->statusFiltersSidebar)
    ->append($this->storedFiltersSidebar)
    ->append($this->batches);
?>
<?php $this->headLink()->appendStylesheet($this->basePath() . Orders\Module::PUBLIC_FOLDER . 'css/orders.css') ?>
<div id="main" class="module clearfix<?= $this->placeholder('#main.class')->setPrefix(' ')->setIndent(1) ?>">
<?= $this->breadcrumbs; ?>
<?= $this->bulkItems; ?>
<?= $this->ordersTable; ?>
</div>
