<?php $this->inlineScript()->captureStart(); ?>
$("#datatable").on("fnServerData", function(event, sSource, aoData, fnCallback, oSettings) {
    $("#filters input[name], #filters select[name]").each(function() {
        aoData.push({"name": "filter[" + $(this).attr("name") + "]", "value": $(this).val()});
    });
    aoData.push({"name": "batch", "value": $('#hidden_batch_filter').val()});
});

$("#filters input[name='apply-filters']").on("click", function() {
    $("#datatable").cgDataTable("redraw");
});

$("#filters input[name='clear-filters']").on("click", function() {
    $("#filters input[name][type!='button'], #filters select[name]").val(undefined);
    $("#datatable").cgDataTable("redraw");
});

function batchFilter(batchId) {
    $('#hidden_batch_filter').val(batchId);
    $("#filters input[name='clear-filters']").click();
}

$(document).on('click', '.batch-filter', function(e) {
    e.preventDefault();
    batchFilter($(this).attr('data-batch-id'));
    return false;
});

$("#datatable").on("renderColumn", function(event, cgmustache, template, column, data) {
    data.datatable = $(this).attr("id");
    data.formatCurrency = cgmustache.formatCurrency(data);
    data.formatDateTime = cgmustache.formatDateTime(data);
    data.formatAdditionalOrderItems = function()
    {
        return function(variable, render) {
            data.extraItems = JSON.parse(JSON.stringify(data.items));
            data.extraItems.splice(0, 1);
            return render(variable);
        };
    };
    data.order_url = Mustache.render("<?= urldecode($this->url('Orders/order', ['order' => '{{order}}'])) ?>", {order: data.id});
    data.tag_url = "<?= $this->url('Orders/tag') ?>";
    data.hasTag = function() {
        return function(variable, render) {
            if ($.inArray(variable, data.tag)) {
                return " checked=\"checked\"";
            }
        }
    };
});

$("#datatable").on("fnRowCallback", function(event, nRow, aData, iDisplayIndex, iDisplayIndexFull) {
    $("a.title", nRow).cgPjax();
});
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->headScript()->appendFile($this->basePath() . CG_UI\Module::PUBLIC_FOLDER . 'js/mustache.js'); ?>
<?php $this->headScript()->appendFile($this->basePath() . CG_UI\Module::PUBLIC_FOLDER . 'js/cg-mustache.js'); ?>
<?php $this->headScript()->appendFile($this->basePath() . CG_UI\Module::PUBLIC_FOLDER . 'js/jquery/cg-pjax.js'); ?>
<?php $this->placeholder('#main.class')->append('full-width'); ?>
<?php $this->placeholder('#sub-header')->append($filters); ?>
<?php $this->placeholder('#sidebar')->append($batches); ?>
<div id="main" class="module clearfix<?= $this->placeholder('#main.class')->setPrefix(' ')->setIndent(1) ?>">
<?= $this->breadcrumbs; ?>
<?= $this->bulkItems; ?>
<?= $this->ordersTable; ?>
</div>
