<?php $this->headScript()->appendFile($this->basePath() . CG_UI\Module::PUBLIC_FOLDER . 'js/mustache.js'); ?>
<?php $this->headScript()->appendFile($this->basePath() . CG_UI\Module::PUBLIC_FOLDER . 'js/cg-mustache.js'); ?>
<?php $this->placeholder('#sidebar')->set($this->sidebar); ?>
<?php
$fullWidth = false;
$pageTitle = 'Order Page Prototype';
$filters = false;
$title = "View Order";
$bulkActionsClass = 'bulk-actions-inline';
$bulkActions = array( 
    array(  
        'title' => 'Print',
        'class' => 'print',
        'sub-actions' => array( 
              array( 'title' => 'Example 1',         'action' => 'example' ),
              array( 'title' => 'Example 2',         'action' => 'example' )
           )
     ),
    array(  
        'title' => 'Dispatch',
        'class' => 'dispatch'
     ),
    array(  
        'title' => 'Tag / Untag',
        'class' => 'tag-untag',
        'sub-actions' => array( 
              array( 'title' => 'Example 1',         'action' => 'example' ),
              array( 'title' => 'Example 2',         'action' => 'example' )
           )
     ),
    array(  
        'title' => 'Courier',
        'class' => 'courier',
        'sub-actions' => array( 
              array( 'title' => 'Example 1',         'action' => 'example' ),
              array( 'title' => 'Example 2',         'action' => 'example' )
           )
     ),
    array(  
        'title' => 'Accounting',
        'class' => 'accounting',
        'sub-actions' => array( 
              array( 'title' => 'Example 1',         'action' => 'example' ),
              array( 'title' => 'Example 2',         'action' => 'example' )
           )
     )
 );
?>
<div id="order-status" class="red-bg">New</div>
<div id="breadcrumbs" class="order-breadcrumbs">
    <ul>
        <li><a href="#">View Order</a></li>
        <li class="separator"><span>&nbsp;</span></li>
        <li><span>1056609</span></li>
    </ul>
    <div class="right">
        <span><strong>Order ID: </strong>1056609</span>
        <img src="/channelgrabber/zf2-v4-ui/img/logos/ebay.png" alt="eBay" />
    </div>
</div>
<div id="bulk-actions" class="module full-width with-padding clearfix bulk-actions-inline">
    <div class="bulk-action  with-select">
    <div class="default clearfix">
        <span class="action" data-action="print">
            <span class="icon-med inverted print">&nbsp;</span>
            <span class="title">Print</span>
        </span>
                    <span class="divider">
            <span class="arrow down">&nbsp;</span>
        </span>
    </div>
    <ul> 
        <span class="box-arrow-up"></span>
        <li><a href="#" class="action" data-action="example"><span>Example 1</span></a></li>
        <li><a href="#" class="action" data-action="example"><span>Example 2</span></a></li>
    </ul>
    </div>
    <div class="bulk-action ">
    <div class="default clearfix">
        <span class="action" data-action="dispatch">
            <span class="icon-med inverted dispatch">&nbsp;</span>
            <span class="title">Dispatch</span>
        </span>
                </div>
        </div>
    <div class="bulk-action  with-select">
    <div class="default clearfix">
        <span class="action" data-action="tag-untag">
            <span class="icon-med inverted tag-untag">&nbsp;</span>
            <span class="title">Tag / Untag</span>
        </span>
                    <span class="divider">
            <span class="arrow down">&nbsp;</span>
        </span>
    </div>
    <ul>
    <span class="box-arrow-up"></span>
                    <li><a href="#" class="action" data-action="example"><span>Example 1</span></a></li>
                    <li><a href="#" class="action" data-action="example"><span>Example 2</span></a></li>
                </ul>
        </div>
    <div class="bulk-action  with-select">
    <div class="default clearfix">
        <span class="action" data-action="courier">
            <span class="icon-med inverted courier">&nbsp;</span>
            <span class="title">Courier</span>
        </span>
                    <span class="divider">
            <span class="arrow down">&nbsp;</span>
        </span>
    </div>
    <ul>
    <span class="box-arrow-up"></span>
                    <li><a href="#" class="action" data-action="example"><span>Example 1</span></a></li>
                    <li><a href="#" class="action" data-action="example"><span>Example 2</span></a></li>
                </ul>
        </div>
    <div class="bulk-action  with-select">
    <div class="default clearfix">
        <span class="action" data-action="accounting">
            <span class="icon-med inverted accounting">&nbsp;</span>
            <span class="title">Accounting</span>
        </span>
                    <span class="divider">
            <span class="arrow down">&nbsp;</span>
        </span>
    </div>
    <ul>
        <span class="box-arrow-up"></span>
        <li><a href="#" class="action" data-action="example"><span>Example 1</span></a></li>
        <li><a href="#" class="action" data-action="example"><span>Example 2</span></a></li>
    </ul>
</div>
<a href="#" class="button close-popup">Back to Orders</a>
</div>
<?=$this->timelineBoxes ?>
<div class="module clearfix">
    <form class="single-row">
        <label>
            <span class="icon-large warning"></span>
            <span class="label">Order Alert:</span>
            <input type="text" class="text" placeholder="Order Alert" name=""/>
            <input type="submit" class="button inline" value="Save Alert" />
        </label>
    </form>
</div>
<div class="module clearfix">
    <form class="single-row">
        <label>
            <span class="icon-large user"></span>
            <span class="label">Buyer Message:</span>
            <p>Hello please leave it next door...</p>
        </label>
    </form>
</div>
<div class="module clearfix">
    <div id="detailsForm">
        <form action="" method="post" class="ajaxPost">
            <div class="half" id="billing-information">
                <h2>Billing Information</h2>
                <label>
                    <span>Recipient Name</span>
                    <abbr class="required">*</abbr>
                    <input type="text" name="companyName" required="required" placeholder="John Smith">
                </label>
                <label>
                    <span>Company Name</span>
                    <input type="text" name="companyName" required="required" placeholder="">
                </label>
                <label>
                    <span>Address Line 1</span>
                    <abbr class="required">*</abbr>
                    <input type="text" name="addressLine1" required="required" placeholder="123 The Street" value="">
                </label>
                <label>
                    <span>Address Line 2</span>
                    <input type="text" name="addressLine2" placeholder="My Town" value="">
                </label>
                <label>
                    <span>City</span>
                    <abbr class="required">*</abbr>
                    <input type="text" name="city" required="required" placeholder="Manchester" value="">
                </label>
                <label>
                    <span>County</span>
                    <input type="text" name="county" placeholder="Lancashire" value="">
                </label>
                <label>
                    <span>Postcode</span>
                    <input type="text" name="postcode" placeholder="AB1 2CD" value="">
                </label>
                <label>
                    <span>Country</span>
                    <div class="input">
                        <div class="custom-select">
                            <div class="selected">Select <span class="arrow down">&nbsp;</span></div>
                            <ul>
                                <li><a href="#">United Kingdom</a></li>
                                <li><a href="#">Afghanistan</a></li>
                                <li><a href="#">Azerbaijan</a></li>
                            </ul>
                        </div>
                    </div>
                </label>
                <label>
                    <span>Telephone</span>
                    <input type="text" name="county" placeholder="Lancashire" value="">
                </label>
            </div>
            <div class="half"  id="buyer-information">
                <h2>Buyer Information</h2>
                <div class="duplicate-data-checkbox">
                    <input type="checkbox" class="duplicate-data" data-source="billing-information" data-target="buyer-information"/>
                    <span>Same as billing: </span>
                </div>
                <label>
                    <span>Buyer Name</span>
                    <abbr class="required">*</abbr>
                    <input type="text" name="companyName" required="required" placeholder="John Smith">
                </label>
                <label>
                    <span>Company Name</span>
                    <input type="text" name="companyName" required="required" placeholder="">
                </label>
                <label>
                    <span>Address Line 1</span>
                    <abbr class="required">*</abbr>
                    <input type="text" name="addressLine1" required="required" placeholder="123 The Street" value="">
                </label>
                <label>
                    <span>Address Line 2</span>
                    <input type="text" name="addressLine2" placeholder="My Town" value="">
                </label>
                <label>
                    <span>City</span>
                    <abbr class="required">*</abbr>
                    <input type="text" name="city" required="required" placeholder="Manchester" value="">
                </label>
                <label>
                    <span>County</span>
                    <input type="text" name="county" placeholder="Lancashire" value="">
                </label>
                <label>
                    <span>Postcode</span>
                    <input type="text" name="postcode" placeholder="AB1 2CD" value="">
                </label>
                <label>
                    <span>Country</span>
                    <div class="input">
                        <div class="custom-select">
                            <div class="selected">Select <span class="arrow down">&nbsp;</span></div>
                            <ul>
                                <li><a href="#">United Kingdom</a></li>
                                <li><a href="#">Afghanistan</a></li>
                                <li><a href="#">Azerbaijan</a></li>
                            </ul>
                        </div>
                    </div>
                </label>
                <label>
                    <span>Telephone</span>
                    <input type="text" name="county" placeholder="Lancashire" value="">
                </label>
            </div>
            <div class="half" style="clear:both; padding-top:0px;">
                <label>
                    <input type="submit" name="save" class="button form-button" value="Save"> 
                    <span class="loading">Saving</span>
                </label>
            </div>
        </form>
    </div>
</div>

<div class="module clearfix">
    <h2>Product &amp; Payment Information</h2>
    <?= $this->productPaymentTable ?>
    <table class="no-borders">
        <tr>
            <td colspan="2">Paid By: <strong>Paypal</strong></td>
            <td class="right"><strong>Postage:</strong></td>
            <td class="right"><strong>&pound;2.50</strong></td>
        </tr>
        <tr>
            <td colspan="2">Reference: <strong>644864684</strong></td>
            <td class="right"><strong>Total:</strong></td>
            <td class="right"><strong>&pound;17.50</strong></td>
        </tr>
    </table>
    <form  method="post" class="ajaxPost">
        <label>
            <span>Refund Amount &pound;</span>
            <input type="text" name="companyName" required="required" placeholder="" value="">
        </label>
        <label>
            <span>Refund Reason</span>
            <div class="input">
                <div class="custom-select">
                    <div class="selected">Select <span class="arrow down">&nbsp;</span></div>
                    <ul>
                        <li><a href="#">Some reason</a></li>
                        <li><a href="#">Another reason</a></li>
                        <li><a href="#">And Another Reason</a></li>
                    </ul>
                </div>
            </div>
        </label>
        <label>
            <input type="submit" name="save" class="button form-button" value="Refund"> 
            <span class="loading">Refunding</span>
        </label>
    </form>
</div>
<div class="module clearfix">
    <h2>Shipping</h2>
    <form  method="post" class="ajaxPost">
        <label>
            <span>Shipping Service</span>
            <div class="input">
                <?php
                $data =  array(
                    'options' =>array( 
                        array( 'img' => '/channelgrabber/zf2-v4-ui/img/logos/royalmail.png', 'href' => '#',   'title' => 'Royal Mail',  'class' => '' ),
                        array( 'img' => '/channelgrabber/zf2-v4-ui/img/logos/dpd.png', 'href' => '#',         'title' => 'DPD',  'class' => '' ),
                        array( 'img' => '/channelgrabber/zf2-v4-ui/img/logos/interlink.png', 'href' => '#',   'title' => 'Interlink',     'class' => '' ),
                        array( 'img' => '/channelgrabber/zf2-v4-ui/img/logos/parcelforce.png', 'href' => '#', 'title' => 'Parcel Force', 'class' => '' )
                    ),
                    'customSelectImgSrc' => '/channelgrabber/zf2-v4-ui/img/logos/royalmail.png'
                );
                ?>
                <?= $this->partial('elements/custom-select-image', $data); ?>
                <?php // include('includes/layout/custom/custom-select-image.php'); ?>
            </div>
        </label>
        <label>
            <span>Tracking Number</span>
            <input type="text" name="companyName" required="required" placeholder="My Company Ltd"  value="GB 1234567890">
        </label>
    </form>
</div>
<div class="module clearfix">
    <h2>Accounting</h2>
    <?=$this->accountingTable; ?>
</div>
<?= $this->notes ?>