<?php
use CG\Order\Shared\Tracking\Status as OrderTrackingStatus;
use CG_UI\Form\Element\Text\Country as CountrySelect;
?>
<?php $this->inlineScript()->captureStart(); ?>
    $('form').submit(function() {
        return false;
    });
    require.config({
        paths: {
            'Orders': "<?= $this->basePath() . Orders\Module::PUBLIC_FOLDER . 'js';?>"
        }
    });
require([
        "note/NoteDomAccess",
        "note/Notes",
        "note/Note",
        "orderDetails/OrderDetailsSidebar",
        "address/Address",
        "alert/Alert",
        "orderDetails/OrderDetailsPage",
        "tracking/orderTracking",
        "Clipboard"
    ],
    function(NoteDomAccess, Notes, Note, OrderDetailsSidebar, Address, Alert, OrderDetailsPage, OrderTracking, Clipboard) {
        //References to n need to be migrated, it is the notification library
        var noteDomAccess = new NoteDomAccess('#notes', '#note-input', CGMustache);
        var notes = new Notes(noteDomAccess, n, Note);
        var sidebar = new OrderDetailsSidebar();
        var address = new Address(n, '#addressInformation');
        var orderTracking = new OrderTracking(n, '#trackingInformation');
        var alert = new Alert(n, '#alert');
        var orderDetailsPage = new OrderDetailsPage(sidebar, address, notes, alert, orderTracking);

        var billingClipboard = new Clipboard(
            '#copy-billing-address',
            $('#billing-information').find('label input.copy-address')
        );
        <?php if (!$order->getFulfilmentAddress()): ?>
        var shippingClipboard = new Clipboard(
            '#copy-shipping-address',
            $('#shipping-information').find('label input.copy-address')
        );
        <?php else: ?>
        var fulfilmentClipboard = new Clipboard(
            '#copy-shipping-address',
            $('#fulfilment-information')
        );
        <?php endif; ?>

});
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->placeholder('#sidebar')->set($this->sidebar); ?>


<div class="bulk-actions-section clearfix section-seperator">
    <div class="orderid-logo-holder">
        <?= $this->accountDetails ?>
        <?= $this->orderDetails ?>
        <?= $this->status ?>
    </div>
    <div class="bulk-actions-holder">
      <?= $this->bulkActions ?>
    </div>
</div>

<div class="module clearfix section-seperator timeline" id="timeline">
    <?= $this->timelineBoxes; ?>
</div>

<div class="module clearfix section-separator" id="order-alert">
    <form class="single-row" id="alert" data-url="<?= $this->url('Orders/order/alert', array('order' => $order->getId())); ?>"
          data-actionMessage="<?= $this->translate('Saving alert'); ?>" data-successMessage="<?= $this->translate('Alert saved'); ?>">
        <label>
            <span class="sprite-alert-tri-28-black"></span>
            <span class="large-heading-left"><?= $this->translate('Order Alert'); ?>:</span>
            <?php
                $alerts = $order->getAlerts();
                $alerts->rewind();
                $alert = $alerts->current();
            ?>
            <div class="order-alert-inputholder">
                <input type="text" class="inputbox" name="" value="<?= ($alert) ? $alert->getAlert() : ""; ?>" id="input"/>
            </div>
            <input type="hidden" value="<?= ($alert) ? $alert->getStoredETag() : ""; ?>" id="eTag"/>
            <div class="order-alert-button">
                <input type="submit" class="button inline alert-save" value="<?= $this->translate('Save Alert'); ?>"/>
            </div>
        </label>
    </form>
</div>
<div class="module clearfix section-separator" id="order-buyer-message">
    <form class="single-row">
        <label>
            <span class="sprite-user-28-black"></span>
            <span class="large-heading-left">Buyer Message:</span>
            <p class="buyer-message"><?= $order->getBuyerMessage() ?: $this->translate("There is no buyer message for this order"); ?></p>
        </label>
    </form>
</div>
<div class="module clearfix section-separator">
    <div id="detailsForm">
        <form id="addressInformation" data-url="<?= $this->url('Orders/order/address', array('order' => $order->getId())); ?>"
              data-actionMessage="<?= $this->translate('Updating address'); ?>" data-successMessage="<?= $this->translate('Address updated'); ?>">
            <input type="hidden" id="eTag" name="eTag" value="<?= $order->getUserChange() ? $order->getUserChange()->getStoredETag() : null; ?>">
            <div class="half" id="billing-information">
                <span class="heading-large heading-spacing"><?= $this->translate('Billing Information'); ?>
                    <a class="copy-address-to-clipboard" id="copy-billing-address"><?= $this->translate("Copy address to clipboard"); ?></a>
                </span>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Buyer Name'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="billingAddressFullName" value="<?= $order->getCalculatedBillingAddressFullName(); ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Company Name'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="billingAddressCompanyName" value="<?= $order->getCalculatedBillingAddressCompanyName(); ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Address Line 1'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="billingAddress1" value="<?= $order->getCalculatedBillingAddress1(); ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Address Line 2'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="billingAddress2" value="<?= $order->getCalculatedBillingAddress2(); ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Address Line 3'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="billingAddress3" value="<?= $order->getCalculatedBillingAddress3(); ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('City'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="billingAddressCity" value="<?= $order->getCalculatedBillingAddressCity(); ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('County'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="billingAddressCounty" value="<?= $order->getCalculatedBillingAddressCounty(); ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Postcode'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="billingAddressPostcode" value="<?= $order->getCalculatedBillingAddressPostcode(); ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Country'); ?></span>
                    <?=
                    $this->mustache(
                        'elements/custom-select.mustache',
                        [
                            'holder' => 'order-inputbox-holder',
                            'class' => 'copy-address',
                            'name' => 'billingAddressCountry',
                            'searchField' => true,
                            'blankOption' => true,
                            'options' => CountrySelect::getDefaultCountryOptions($order->getCalculatedBillingAddressCountry()),
                            'disabled' => !$this->editable,
                        ]
                    )
                    ?>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Email'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox" type="text" name="billingEmailAddress" value="<?= $order->getCalculatedBillingEmailAddress(); ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Telephone'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox" type="text" name="billingPhoneNumber" value="<?= $order->getCalculatedBillingPhoneNumber(); ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
            </div>
            <div class="half"  id="shipping-information">
                <span class="heading-large heading-spacing"><?= $this->translate('Shipping Information'); ?>
                    <a class="copy-address-to-clipboard" id="copy-shipping-address"><?= $this->translate("Copy address to clipboard"); ?></a>
                </span>
                <?php if (!$order->getFulfilmentAddress()): ?>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Recipient Name'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="shippingAddressFullName" value="<?= $order->getCalculatedShippingAddressFullName(); ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Company Name'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="shippingAddressCompanyName" value="<?= $order->getCalculatedShippingAddressCompanyName(); ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Address Line 1'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="shippingAddress1" value="<?= $order->getCalculatedShippingAddress1(); ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Address Line 2'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="shippingAddress2" value="<?= $order->getCalculatedShippingAddress2(); ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Address Line 3'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="shippingAddress3" value="<?= $order->getCalculatedShippingAddress3(); ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('City'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="shippingAddressCity" value="<?= $order->getCalculatedShippingAddressCity(); ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('County'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="shippingAddressCounty" value="<?= $order->getCalculatedShippingAddressCounty(); ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Postcode'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox copy-address" type="text" name="shippingAddressPostcode" value="<?= $order->getCalculatedShippingAddressPostcode(); ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Country'); ?></span>
                    <?=
                    $this->mustache(
                        'elements/custom-select.mustache',
                        [
                            'holder' => 'order-inputbox-holder',
                            'class' => 'copy-address',
                            'name' => 'shippingAddressCountry',
                            'searchField' => true,
                            'blankOption' => true,
                            'options' => CountrySelect::getDefaultCountryOptions($order->getCalculatedShippingAddressCountry()),
                            'disabled' => !$this->editable,
                        ]
                    )
                    ?>
                </label>
                <?php else: ?>
                <fieldset class='inputbox'>
                    <legend><?=$this->translate('eBay Global Shipping');?></legend>
                    <p id='fulfilment-information'><?=
                        ($order->getFulfilmentAddress()->getAddressFullName() ? $order->getFulfilmentAddress()->getAddressFullName() . '<br />' : '') .
                        ($order->getFulfilmentAddress()->getAddressCompanyName() ? $order->getFulfilmentAddress()->getAddressCompanyName() . '<br />' : '') .
                        $order->getFulfilmentAddress()->getAddress1() . '<br />' .
                        $order->getFulfilmentAddress()->getAddress2() . '<br />' .
                        ($order->getFulfilmentAddress()->getAddress3() ? $order->getFulfilmentAddress()->getAddress3() . '<br />' : '') .
                        ($order->getFulfilmentAddress()->getAddressCity() ? $order->getFulfilmentAddress()->getAddressCity() . '<br />' : '') .
                        ($order->getFulfilmentAddress()->getAddressCounty() ? $order->getFulfilmentAddress()->getAddressCounty() . '<br />' : '') .
                        $order->getFulfilmentAddress()->getAddressPostcode() . '<br />' .
                        $order->getFulfilmentAddress()->getAddressCountry()
                    ;?></p>
                </fieldset>
                <?php endif; ?>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Email'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox" type="text" name="shippingEmailAddress" value="<?= $order->getCalculatedShippingEmailAddress(); ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
                <label>
                    <span class="inputbox-label"><?= $this->translate('Telephone'); ?></span>
                    <div class="order-inputbox-holder">
                        <input class="inputbox" type="text" name="shippingPhoneNumber" value="<?= $order->getCalculatedShippingPhoneNumber(); ?>"<?php if (!$this->editable): ?> readonly="readonly"<?php endif; ?> />
                    </div>
                </label>
            </div>
            <?php if ($this->editable): ?>
            <div class="half" style="clear:both; padding-top:0px;">
                <label>
                    <input type="submit" name="save" class="button form-button address-button" value="<?= $this->translate('Save'); ?>">
                </label>
            </div>
            <?php endif; ?>
        </form>
    </div>
</div>
<?php if ($this->editable): ?>
<div class="module clearfix section-separator" id="tracking-information">
    <span class="heading-large heading-spacing"><?= $this->translate('Shipping'); ?></span>
    <form id="trackingInformation"
          data-url="<?= $this->url('Orders/order/tracking', array('order' => $order->getId())); ?>"
          data-actionMessage="<?= $this->translate('Updating tracking info'); ?>"
          data-confirmMessage="<?= $this->translate('You have used this tracking number before, you may have an error when dispatching. Do you wish to continue using this tracking number?'); ?>"
          data-successMessage="<?= $this->translate('Tracking info updated'); ?>"
        >
        <div class="half">
        <?php if (isset($this->printShippingLabelButton)): ?>
        <label>
            <span class="inputbox-label"><?= $this->translate('Label'); ?></span>
            <div class="alternate-input">
                <?= $this->printShippingLabelButton ?>
            </div>
        </label>
        <?php endif; ?>
        <label>
            <span class="inputbox-label"><?= $this->translate('Carrier'); ?></span>
            <div class="order-inputbox-holder">
                <?= $this->carrierSelect ?>
            </div>
        </label>
        <label>
            <span class="inputbox-label"><?= $this->translate('Tracking Number'); ?></span>
            <div class="order-inputbox-holder">
                <input class="inputbox" id="trackingNumber" type="text" name="trackingNumber" value="<?= ($tracking) ? $tracking->getNumber() : ""; ?>">
            </div>
            <?php if ($tracking && $tracking->getStatus() == OrderTrackingStatus::ERROR): ?>
            <div class="sprite-alert-tri-28-black" title="There was a problem sending the tracking number to the channel" style="float: left; margin-left: 20px;"></div>
            <?php endif; ?>
        </label>
        <input type="hidden" value="<?= ($tracking) ? $tracking->getStoredETag() : ""; ?>" id="eTag" name="eTag"/>
        <div class="half" style="clear:both; padding-top:0px;">
            <div class="order-inputbox-holder">
                <input type="submit" name="save" class="button form-button tracking-button" value="<?= $this->translate('Save'); ?>">
            </div>
        </div>
        </div>
    </form>
</div>
<?php endif; ?>
<div id="product-payment-table" class="module clearfix section-separator">
    <span class="heading-large heading-spacing"><?= $this->translate('Product & Payment Information'); ?></span>
    <?php if(count($order->getItems())):?>
        <div id="products-table">
          <?= $this->productPaymentTable; ?>
        </div>
    <?php else: ?>
        <p><?= $this->translate('This order has no items'); ?></p>
    <?php endif;?>
    <table class="no-borders totals-table">
        <tr>
            <td class="leftcell" class="left">
                <?php if ($order->getPaymentMethod()): ?>
                    <strong><?= $this->translate('Paid Via'); ?>:</strong> <?= $order->getPaymentMethod() ?>
                <?php endif; ?>
            </td>
            <td class="midcell"><strong><?= $this->translate('Postage & Packing'); ?>:</strong></td>
            <td class="rightcell"><?= $this->currencyFormat($order->getShippingPrice(), $order->getCurrencyCode()); ?></td>
        </tr>
        <tr>
            <td class="leftcell"></td>
            <td class="midcell"><strong><?= $this->translate('Subtotal'); ?>:</strong></td>
            <td class="rightcell"><?= $this->currencyFormat($order->getSubtotal(), $order->getCurrencyCode()); ?></strong></td>
        </tr>
        <?php if ($rootOu->isVatRegistered()): ?>
        <tr>
            <td class="leftcell">
                <?php if ($order->getPaymentReference()): ?>
                    <?= $this->translate('Reference'); ?>: <strong><?= $order->getPaymentReference() ?></strong>
                <?php endif; ?>
            </td>
            <td class="midcell"><strong><?= $this->translate('VAT'); ?>:</strong></td>
            <td class="rightcell"><?= $this->currencyFormat($order->getTax(), $order->getCurrencyCode()); ?></strong></td>
        </tr>
        <?php endif; ?>
        <tr>
            <td class="leftcell"></td>
            <td class="midcell"><strong><?= $this->translate('Total'); ?>:</strong></td>
            <td class="rightcell"><?= $this->currencyFormat($order->getTotal(), $order->getCurrencyCode()); ?></strong></td>
        </tr>
    </table>
</div>
<div id="order-notes">
    <?= $this->notes ?>
</div>
