<?php $this->inlineScript()->captureStart(); ?>
require.config({
    paths: {
        'Filters': "<?= $this->basePath() . Filters\Module::PUBLIC_FOLDER . 'js';?>"
    }
});
require(["Filters/FilterCollection"], function(filterCollection) {
    filterCollection.setFilters(<?=json_encode($this->filterNames);?>);
});
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->headScript()->appendFile($this->basePath() . Filters\Module::PUBLIC_FOLDER . 'js/dataTableFilters.js'); ?>

<?php $this->placeholder('#sub-header')->append($filters); ?>
<div id="product-stock-logs">
    <div class="module clearfix">
        <div class="heading-large">
            <div class="product-image"><img src="<?=$this->productDetails['image'];?>" /></div>
            <span class="product-details"><?= $this->productDetails['name']; ?>, <?= $this->productDetails['sku']; ?></span>
        </div>
    </div>
    <div class="datatable-container">
        <?=$this->stockLogTable;?>
    </div>
</div>