<div class="setup-wizard-messages-account-section section-separator">
    <?= $this->badge; ?>
    <div class="setup-wizard-messages-account-section-body <?=($this->setupRequired ? 'setup-required' : 'setup-done');?>">
        <?php if ($this->setupRequired) {
            echo $this->partial('setup-wizard/messages/accountSection/setupRequired.phtml', compact('name', 'setupButton'));
        } else {
            echo $this->partial('setup-wizard/messages/accountSection/setupDone.phtml', compact('originalEmailAddress', 'id'));
        } ?>
    </div>
</div>