<div id="setup-wizard-messages-amazon-setup-instructions">
    <ol>
        <li>
            <img src="<?=SetupWizard\Module::PUBLIC_FOLDER;?>img/messages/point1.png" />
            <div class="setup-wizard-messages-list-text">
                <?=$this->translate('Copy email address below');?><br />
                <input class="inputbox" type="email" readonly="readonly" value="<?=$this->email;?>" />
            </div>
        </li>
        <li>
            <img src="<?=SetupWizard\Module::PUBLIC_FOLDER;?>img/messages/point2.png" />
            <div class="setup-wizard-messages-list-text">
                <?=$this->translate('Click this button to go to your Amazon settings (opens in a new window)');?>
            </div>
            <?=$this->amazonSettingsButton;?>
        </li>
        <li>
            <img src="<?=SetupWizard\Module::PUBLIC_FOLDER;?>img/messages/point3.png" />
            <div class="setup-wizard-messages-list-text">
            <?=$this->translate('Paste the above email address into');?>:
            <ul id="setup-wizard-messages-amazon-email-field-list">
                <li>&ndash; Customer Service Email</li>
                <li>&ndash; Customer Service Reply To Email</li>
            </ul>
            <?=$this->translate('Then click \'Submit\'.');?>
            </div>
        </li>
    </ol>
    <div id="setup-wizard-messages-amazon-setup-small-screenshot">
        Screenshot:
        <img src="<?=SetupWizard\Module::PUBLIC_FOLDER;?>img/messages/screenshot-seller-central-email-settings.png" />
    </div>
    <p><?=$this->translate('Once you\'ve done that click the \'Done\' button below.');?></p>
</div>
<script type="text/javascript">
    require(['<?=SetupWizard\Module::PUBLIC_FOLDER;?>/js/steps/Messages/Setup.js'], function(Setup)
    {
        new Setup();
    });
</script>