<div id="setup-wizard-demo">
    <div id="demo">
        <div class="demo-info">
            <div>In order to use ChannelGrabber effectively and ensure it is the right solution for you, <br/>
                we strongly recommend having a demonstration with one of our friendly staff. <br/>
                They can help you make your decision -<br />
                Please book a demonstration through the link below <br/>
                ...Or email sales@channelgrabber.com for a swift response
            </div>
            <div class="demo-link">
                <a target="_blank" href="<?= $this->demoLink ?>">BOOK A DEMO</a>
            </div>
            <div class="callUs">Or call us on <?= $this->phoneNumber ?></div>
        </div>
    </div>
</div>