<div id="setup-wizard-demo">
    <div id="demo" class="half">
        <div class="demo-info">
            <div>In order to use ChannelGrabber effectively and ensure it is the right solution for you, we strongly recommend having a demonstration with one of our friendly staff so they can help you make your decision <br /> Please book a demonstration through the link below or email sales@channelgrabber.com for a swift response</div>
            <div class="demo-link">
                <a target="_blank" href="<?= $this->demoLink ?>">BOOK A DEMO</a>
            </div>
            <div class="callUs">Or call us on <?= $this->phoneNumber ?></div>
        </div>
    </div>
</div>