<?php
use CG\ShipStation\Account as ShipStationAccountService;
use CG_Channel\Module as ChannelModule;
use ShipStation\Module;

// Deliberately not rendering the 'Renew Connection' button as ShipStation don't allow it
/*
$setupRoute = implode('/', [
    Module::ROUTE,
    ShipStationAccountService::ROUTE_SETUP
]);
$url = $this->url($setupRoute, ['channel' => $account->getChannel()]) . '?accountId=' . $account->getId();
echo $this->partial(ChannelModule::TEMPLATE_TOKEN_RENEWAL_HREF, compact('account', 'form', 'route', 'url'));
*/
?>
<?php $mark = true;?>
<div class="module clearfix shippingLedger usps">
    <div class="clearfix balance">
        <span class="heading-large">Please note that postage purchases are made with USPS and are non-refundable</span>
        <div class="status">
            <span class="heading-large">Balance: <?=$currencySymbol;?><?=$balance;?></span>
        </div>
        <button id="topUp" name="topUp" class="button inline account-save pull-left">Purchase $100 credit</button>
    </div>
    <span class="inputbox-label">Auto Top-up:</span>
    <div class="alternate-input mustache">
        <div class="enable-switch-auto-top-up">
            <?= $autoTopUpToggle ?>
        </div>
    </div>
    <div class="tooltip-holder">
        <span class="fa fa-question-circle-o fa-2x" id="topupTooltip" name="topupTooltip"></span>
        <?= $autoTopUpTooltip ?>
    </div>
</div>
<?php if (! empty($clearbooksStatementUrl)) : ?>
    <div class="module clearfix">
        <span class="heading-large heading-spacing">Full ClearBooks Statement</span>
        <iframe src="<?= $clearbooksStatementUrl ?>" class="clearbooks-statement-url-frame"></iframe>
    </div>
<?php endif; ?>
<script type="text/javascript">
    require(['<?=ShipStation\Module::PUBLIC_FOLDER;?>/js/Account/Settings.js'], function(Settings)
    {
        $(document).ready(function() {
            new Settings({"accountId": <?=$account->getId();?>});
        });
    });
</script>