<div id="sidebar" class="clearfix fixed-scroll setup-wizard-sidebar">
    <div class="container clearfix">
        <div class="logo" style="padding-top: 15px;">
            <a href="/"><img src="/channelgrabber/zf2-v4-ui/img/channelgrabber-logo-white-large.png" style="width: 212px; height: 24px;"></a>
        </div>
    </div>
    <div class="filter-module clearfix navbar-content">
        <?= $this->cgnavigation('setup-navigation')->menu()->setUlClass('module-content nav')->render(); ?>
    </div>
</div>