<?php $this->inlineScript()->captureStart(); ?>
require.config({
    paths: {
        'PurchaseOrders': '<?= $this->basePath() . Products\Module::PUBLIC_FOLDER; ?>js/PurchaseOrders'
    }
});
require([
        'PurchaseOrders/PurchaseOrders',
    ],
    function(
        PurchaseOrders
    ) {
    var purchaseOrders = new PurchaseOrders(document.getElementById('purchase-orders-mount-node'), '<?= $this->basePath() . Products\Module::PUBLIC_FOLDER; ?>img');
});
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->placeholder('#main.class')->append('full-width'); ?>
<div id="purchase-orders-mount-node">
</div>
<style>
    /**
      This is a hack to hide the sidebar away for now TODO: Remove this
      When introducing filters (ie Saved Filters)
    **/
    .sidebar-hidden #main-wrapper {
        margin-left: 0 !important;
        width:100%;
    }
</style>
