<?php $this->headScript()->captureStart(); ?>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-19196307-1', 'auto', {'allowLinker': true});
ga('require', 'linker');
ga('linker:autoLink', ['channelgrabber.com','www.channelgrabber.com']);
ga('send', 'pageview');
<?php $this->headScript()->captureEnd(); ?>

<?php
//FB tracking pixel
$this->headScript()->captureStart();
?>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '263419924144350');
fbq('track', 'PageView');
<?php $this->headScript()->captureEnd(); ?>
<noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=263419924144350&ev=PageView&noscript=1" /></noscript>

<?php $this->headScript()->setAllowArbitraryAttributes(true)
    ->appendScript(
        'window.__insp = window.__insp || [];'
        . '__insp.push([\'wid\', 1790643289]);'
        . '(function() {'
        . 'function ldinsp(){if(typeof window.__inspld != "undefined") return; window.__inspld = 1; var insp = document.createElement(\'script\'); insp.type = \'text/javascript\'; insp.async = true; insp.id = "inspsync"; insp.src = (\'https:\' == document.location.protocol ? \'https\' : \'http\') + \'://cdn.inspectlet.com/inspectlet.js\'; var x = document.getElementsByTagName(\'script\')[0]; x.parentNode.insertBefore(insp, x); };'
        . 'setTimeout(ldinsp, 500); document.readyState != "complete" ? (window.attachEvent ? window.attachEvent(\'onload\', ldinsp) : window.addEventListener(\'load\', ldinsp, false)) : ldinsp();'
        . '})();',
        'text/javascript',
        ['id' => 'inspectletjs']
    );
?>
<div class="orderhub-register-content">
    <div class="split">
        <div class="split-item split-1-1">
            <?=$this->ekmPoweredByCg?>
            <div class="paragraph">
                <h1>Contact Customer Support</h1>
                <h3 style="margin-top: 30px"><?= $this->failedMessage; ?></h3>
                <?php if ($this->ekmUsername) { ?>
                    <h3 style="margin-top: 40px; font-weight: bold">EKM <?=$this->usernameText?>: <?=$this->ekmUsername?></h3>
                <?php } ?>
            </div>
            <div style="margin-top: 60px" class="paragraph">
                <h3 style="font-weight: bold"><?= $this->statusTitle; ?></h3>
                <h3 style="margin-top: 20px; font-size: 1.4em"><?= $this->statusMessage1; ?></h3>
                <h3 style="margin-top: 20px; font-size: 1.4em"><?= $this->statusMessage2; ?></h3>
                <h3 style="margin-top: 20px; font-size: 1.4em"><?= $this->statusMessage3; ?></h3>
            </div>
        </div>
    </div>
</div>
