<form class="account-form-holder" style="height:auto" id="carrier-account-form" action="<?=$this->saveUrl;?>" method="POST">
    <div class="account-logo">
        <span class="logo-large <?=$this->channelName;?>"></span>
    </div>

    <input type="hidden" id="accountId" name="account" value="<?= $this->accountId; ?>" />
    <input type="hidden" id="channel" name="channel" value="<?= $this->channelName; ?>" />

    <?php if($this->instructions):?>
    <div class="section">
        <?=$this->instructions;?>
    </div>
    <?php endif;?>

    <?php foreach ($this->fields as $field): ?>
    <?php if ($field->getAttribute('type') != 'hidden'): ?>
    <div class="account-field-holder">
        <div class="label">
            <?= $this->translate($field->getOption('label')); ?>:
            <?php if ($field->getOption('required')):?>
            <abbr class="required">*</abbr>
            <?php endif;?>
        </div>
        <div class="text-field">
            <?= $this->formInput($field); ?>
        </div>
    </div>
    <?php else: ?>
    <?= $this->formInput($field); ?>
    <?php endif; ?>
    <?php endforeach; ?>

    <div class="account-form-buttons-holder">
        <?= $this->linkAccount ?>
        <a href='<?= $this->goBackUrl; ?>'><?= $this->goBack ?></a>
    </div>
</form>
<?php $this->inlineScript()->captureStart(); ?>
    $(document).ready(function()
    {
        (function adjustFormPosition()
        {
            var height = $('.account-form-holder').height();
            var halfHeight = Math.floor(height / 2);
            $('.account-form-holder').css('top', 'calc(50% - ' + halfHeight + 'px)');
        })();

        require(["<?= $this->basePath() . CourierAdapter\Module::PUBLIC_FOLDER; ?>/js/RequestCredentials/Service.js"], function(Service) {
            var service = new Service();
        });
    });
<?php $this->inlineScript()->captureEnd(); ?>