<?php $this->inlineScript()->captureStart(); ?>
    require.config({
        paths: {
            'Redux': '<?= $this->basePath() . \Redux\Module::PUBLIC_FOLDER; ?>/js/Redux'
        }
    });
    require(["Redux/Prototype"], function(Prototype) {
        var prototype = new Prototype(document.getElementById('app-mount-node'));
    });
<?php $this->inlineScript()->captureEnd(); ?>
<div id="app-mount-node"></div>
